// Code generated by ent, DO NOT EDIT.

package asset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloverstd/travel-moments/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUpdatedAt, v))
}

// TripID applies equality check predicate on the "trip_id" field. It's identical to TripIDEQ.
func TripID(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldTripID, v))
}

// UploadedByID applies equality check predicate on the "uploaded_by_id" field. It's identical to UploadedByIDEQ.
func UploadedByID(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUploadedByID, v))
}

// OssKey applies equality check predicate on the "oss_key" field. It's identical to OssKeyEQ.
func OssKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldOssKey, v))
}

// Mime applies equality check predicate on the "mime" field. It's identical to MimeEQ.
func Mime(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMime, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldSize, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHeight, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldDurationMs, v))
}

// TakenAt applies equality check predicate on the "taken_at" field. It's identical to TakenAtEQ.
func TakenAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldTakenAt, v))
}

// HlsKey applies equality check predicate on the "hls_key" field. It's identical to HlsKeyEQ.
func HlsKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHlsKey, v))
}

// ThumbKey applies equality check predicate on the "thumb_key" field. It's identical to ThumbKeyEQ.
func ThumbKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldThumbKey, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldSortOrder, v))
}

// IsLivePhoto applies equality check predicate on the "is_live_photo" field. It's identical to IsLivePhotoEQ.
func IsLivePhoto(v bool) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldIsLivePhoto, v))
}

// MotionKey applies equality check predicate on the "motion_key" field. It's identical to MotionKeyEQ.
func MotionKey(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMotionKey, v))
}

// MotionMime applies equality check predicate on the "motion_mime" field. It's identical to MotionMimeEQ.
func MotionMime(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMotionMime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldUpdatedAt, v))
}

// TripIDEQ applies the EQ predicate on the "trip_id" field.
func TripIDEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldTripID, v))
}

// TripIDNEQ applies the NEQ predicate on the "trip_id" field.
func TripIDNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldTripID, v))
}

// TripIDIn applies the In predicate on the "trip_id" field.
func TripIDIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldTripID, vs...))
}

// TripIDNotIn applies the NotIn predicate on the "trip_id" field.
func TripIDNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldTripID, vs...))
}

// UploadedByIDEQ applies the EQ predicate on the "uploaded_by_id" field.
func UploadedByIDEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldUploadedByID, v))
}

// UploadedByIDNEQ applies the NEQ predicate on the "uploaded_by_id" field.
func UploadedByIDNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldUploadedByID, v))
}

// UploadedByIDIn applies the In predicate on the "uploaded_by_id" field.
func UploadedByIDIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldUploadedByID, vs...))
}

// UploadedByIDNotIn applies the NotIn predicate on the "uploaded_by_id" field.
func UploadedByIDNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldUploadedByID, vs...))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldKind, vs...))
}

// OssKeyEQ applies the EQ predicate on the "oss_key" field.
func OssKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldOssKey, v))
}

// OssKeyNEQ applies the NEQ predicate on the "oss_key" field.
func OssKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldOssKey, v))
}

// OssKeyIn applies the In predicate on the "oss_key" field.
func OssKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldOssKey, vs...))
}

// OssKeyNotIn applies the NotIn predicate on the "oss_key" field.
func OssKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldOssKey, vs...))
}

// OssKeyGT applies the GT predicate on the "oss_key" field.
func OssKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldOssKey, v))
}

// OssKeyGTE applies the GTE predicate on the "oss_key" field.
func OssKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldOssKey, v))
}

// OssKeyLT applies the LT predicate on the "oss_key" field.
func OssKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldOssKey, v))
}

// OssKeyLTE applies the LTE predicate on the "oss_key" field.
func OssKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldOssKey, v))
}

// OssKeyContains applies the Contains predicate on the "oss_key" field.
func OssKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldOssKey, v))
}

// OssKeyHasPrefix applies the HasPrefix predicate on the "oss_key" field.
func OssKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldOssKey, v))
}

// OssKeyHasSuffix applies the HasSuffix predicate on the "oss_key" field.
func OssKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldOssKey, v))
}

// OssKeyEqualFold applies the EqualFold predicate on the "oss_key" field.
func OssKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldOssKey, v))
}

// OssKeyContainsFold applies the ContainsFold predicate on the "oss_key" field.
func OssKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldOssKey, v))
}

// MimeEQ applies the EQ predicate on the "mime" field.
func MimeEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMime, v))
}

// MimeNEQ applies the NEQ predicate on the "mime" field.
func MimeNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldMime, v))
}

// MimeIn applies the In predicate on the "mime" field.
func MimeIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldMime, vs...))
}

// MimeNotIn applies the NotIn predicate on the "mime" field.
func MimeNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldMime, vs...))
}

// MimeGT applies the GT predicate on the "mime" field.
func MimeGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldMime, v))
}

// MimeGTE applies the GTE predicate on the "mime" field.
func MimeGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldMime, v))
}

// MimeLT applies the LT predicate on the "mime" field.
func MimeLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldMime, v))
}

// MimeLTE applies the LTE predicate on the "mime" field.
func MimeLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldMime, v))
}

// MimeContains applies the Contains predicate on the "mime" field.
func MimeContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldMime, v))
}

// MimeHasPrefix applies the HasPrefix predicate on the "mime" field.
func MimeHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldMime, v))
}

// MimeHasSuffix applies the HasSuffix predicate on the "mime" field.
func MimeHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldMime, v))
}

// MimeIsNil applies the IsNil predicate on the "mime" field.
func MimeIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldMime))
}

// MimeNotNil applies the NotNil predicate on the "mime" field.
func MimeNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldMime))
}

// MimeEqualFold applies the EqualFold predicate on the "mime" field.
func MimeEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldMime, v))
}

// MimeContainsFold applies the ContainsFold predicate on the "mime" field.
func MimeContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldMime, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldSize, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldHeight))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldDurationMs))
}

// TakenAtEQ applies the EQ predicate on the "taken_at" field.
func TakenAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldTakenAt, v))
}

// TakenAtNEQ applies the NEQ predicate on the "taken_at" field.
func TakenAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldTakenAt, v))
}

// TakenAtIn applies the In predicate on the "taken_at" field.
func TakenAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldTakenAt, vs...))
}

// TakenAtNotIn applies the NotIn predicate on the "taken_at" field.
func TakenAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldTakenAt, vs...))
}

// TakenAtGT applies the GT predicate on the "taken_at" field.
func TakenAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldTakenAt, v))
}

// TakenAtGTE applies the GTE predicate on the "taken_at" field.
func TakenAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldTakenAt, v))
}

// TakenAtLT applies the LT predicate on the "taken_at" field.
func TakenAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldTakenAt, v))
}

// TakenAtLTE applies the LTE predicate on the "taken_at" field.
func TakenAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldTakenAt, v))
}

// TakenAtIsNil applies the IsNil predicate on the "taken_at" field.
func TakenAtIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldTakenAt))
}

// TakenAtNotNil applies the NotNil predicate on the "taken_at" field.
func TakenAtNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldTakenAt))
}

// HlsStatusEQ applies the EQ predicate on the "hls_status" field.
func HlsStatusEQ(v HlsStatus) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHlsStatus, v))
}

// HlsStatusNEQ applies the NEQ predicate on the "hls_status" field.
func HlsStatusNEQ(v HlsStatus) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldHlsStatus, v))
}

// HlsStatusIn applies the In predicate on the "hls_status" field.
func HlsStatusIn(vs ...HlsStatus) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldHlsStatus, vs...))
}

// HlsStatusNotIn applies the NotIn predicate on the "hls_status" field.
func HlsStatusNotIn(vs ...HlsStatus) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldHlsStatus, vs...))
}

// HlsKeyEQ applies the EQ predicate on the "hls_key" field.
func HlsKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldHlsKey, v))
}

// HlsKeyNEQ applies the NEQ predicate on the "hls_key" field.
func HlsKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldHlsKey, v))
}

// HlsKeyIn applies the In predicate on the "hls_key" field.
func HlsKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldHlsKey, vs...))
}

// HlsKeyNotIn applies the NotIn predicate on the "hls_key" field.
func HlsKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldHlsKey, vs...))
}

// HlsKeyGT applies the GT predicate on the "hls_key" field.
func HlsKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldHlsKey, v))
}

// HlsKeyGTE applies the GTE predicate on the "hls_key" field.
func HlsKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldHlsKey, v))
}

// HlsKeyLT applies the LT predicate on the "hls_key" field.
func HlsKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldHlsKey, v))
}

// HlsKeyLTE applies the LTE predicate on the "hls_key" field.
func HlsKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldHlsKey, v))
}

// HlsKeyContains applies the Contains predicate on the "hls_key" field.
func HlsKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldHlsKey, v))
}

// HlsKeyHasPrefix applies the HasPrefix predicate on the "hls_key" field.
func HlsKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldHlsKey, v))
}

// HlsKeyHasSuffix applies the HasSuffix predicate on the "hls_key" field.
func HlsKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldHlsKey, v))
}

// HlsKeyIsNil applies the IsNil predicate on the "hls_key" field.
func HlsKeyIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldHlsKey))
}

// HlsKeyNotNil applies the NotNil predicate on the "hls_key" field.
func HlsKeyNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldHlsKey))
}

// HlsKeyEqualFold applies the EqualFold predicate on the "hls_key" field.
func HlsKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldHlsKey, v))
}

// HlsKeyContainsFold applies the ContainsFold predicate on the "hls_key" field.
func HlsKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldHlsKey, v))
}

// ThumbKeyEQ applies the EQ predicate on the "thumb_key" field.
func ThumbKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldThumbKey, v))
}

// ThumbKeyNEQ applies the NEQ predicate on the "thumb_key" field.
func ThumbKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldThumbKey, v))
}

// ThumbKeyIn applies the In predicate on the "thumb_key" field.
func ThumbKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldThumbKey, vs...))
}

// ThumbKeyNotIn applies the NotIn predicate on the "thumb_key" field.
func ThumbKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldThumbKey, vs...))
}

// ThumbKeyGT applies the GT predicate on the "thumb_key" field.
func ThumbKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldThumbKey, v))
}

// ThumbKeyGTE applies the GTE predicate on the "thumb_key" field.
func ThumbKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldThumbKey, v))
}

// ThumbKeyLT applies the LT predicate on the "thumb_key" field.
func ThumbKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldThumbKey, v))
}

// ThumbKeyLTE applies the LTE predicate on the "thumb_key" field.
func ThumbKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldThumbKey, v))
}

// ThumbKeyContains applies the Contains predicate on the "thumb_key" field.
func ThumbKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldThumbKey, v))
}

// ThumbKeyHasPrefix applies the HasPrefix predicate on the "thumb_key" field.
func ThumbKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldThumbKey, v))
}

// ThumbKeyHasSuffix applies the HasSuffix predicate on the "thumb_key" field.
func ThumbKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldThumbKey, v))
}

// ThumbKeyIsNil applies the IsNil predicate on the "thumb_key" field.
func ThumbKeyIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldThumbKey))
}

// ThumbKeyNotNil applies the NotNil predicate on the "thumb_key" field.
func ThumbKeyNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldThumbKey))
}

// ThumbKeyEqualFold applies the EqualFold predicate on the "thumb_key" field.
func ThumbKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldThumbKey, v))
}

// ThumbKeyContainsFold applies the ContainsFold predicate on the "thumb_key" field.
func ThumbKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldThumbKey, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldSortOrder, v))
}

// IsLivePhotoEQ applies the EQ predicate on the "is_live_photo" field.
func IsLivePhotoEQ(v bool) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldIsLivePhoto, v))
}

// IsLivePhotoNEQ applies the NEQ predicate on the "is_live_photo" field.
func IsLivePhotoNEQ(v bool) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldIsLivePhoto, v))
}

// MotionKeyEQ applies the EQ predicate on the "motion_key" field.
func MotionKeyEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMotionKey, v))
}

// MotionKeyNEQ applies the NEQ predicate on the "motion_key" field.
func MotionKeyNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldMotionKey, v))
}

// MotionKeyIn applies the In predicate on the "motion_key" field.
func MotionKeyIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldMotionKey, vs...))
}

// MotionKeyNotIn applies the NotIn predicate on the "motion_key" field.
func MotionKeyNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldMotionKey, vs...))
}

// MotionKeyGT applies the GT predicate on the "motion_key" field.
func MotionKeyGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldMotionKey, v))
}

// MotionKeyGTE applies the GTE predicate on the "motion_key" field.
func MotionKeyGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldMotionKey, v))
}

// MotionKeyLT applies the LT predicate on the "motion_key" field.
func MotionKeyLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldMotionKey, v))
}

// MotionKeyLTE applies the LTE predicate on the "motion_key" field.
func MotionKeyLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldMotionKey, v))
}

// MotionKeyContains applies the Contains predicate on the "motion_key" field.
func MotionKeyContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldMotionKey, v))
}

// MotionKeyHasPrefix applies the HasPrefix predicate on the "motion_key" field.
func MotionKeyHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldMotionKey, v))
}

// MotionKeyHasSuffix applies the HasSuffix predicate on the "motion_key" field.
func MotionKeyHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldMotionKey, v))
}

// MotionKeyIsNil applies the IsNil predicate on the "motion_key" field.
func MotionKeyIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldMotionKey))
}

// MotionKeyNotNil applies the NotNil predicate on the "motion_key" field.
func MotionKeyNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldMotionKey))
}

// MotionKeyEqualFold applies the EqualFold predicate on the "motion_key" field.
func MotionKeyEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldMotionKey, v))
}

// MotionKeyContainsFold applies the ContainsFold predicate on the "motion_key" field.
func MotionKeyContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldMotionKey, v))
}

// MotionMimeEQ applies the EQ predicate on the "motion_mime" field.
func MotionMimeEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldMotionMime, v))
}

// MotionMimeNEQ applies the NEQ predicate on the "motion_mime" field.
func MotionMimeNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldMotionMime, v))
}

// MotionMimeIn applies the In predicate on the "motion_mime" field.
func MotionMimeIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldMotionMime, vs...))
}

// MotionMimeNotIn applies the NotIn predicate on the "motion_mime" field.
func MotionMimeNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldMotionMime, vs...))
}

// MotionMimeGT applies the GT predicate on the "motion_mime" field.
func MotionMimeGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldMotionMime, v))
}

// MotionMimeGTE applies the GTE predicate on the "motion_mime" field.
func MotionMimeGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldMotionMime, v))
}

// MotionMimeLT applies the LT predicate on the "motion_mime" field.
func MotionMimeLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldMotionMime, v))
}

// MotionMimeLTE applies the LTE predicate on the "motion_mime" field.
func MotionMimeLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldMotionMime, v))
}

// MotionMimeContains applies the Contains predicate on the "motion_mime" field.
func MotionMimeContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldMotionMime, v))
}

// MotionMimeHasPrefix applies the HasPrefix predicate on the "motion_mime" field.
func MotionMimeHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldMotionMime, v))
}

// MotionMimeHasSuffix applies the HasSuffix predicate on the "motion_mime" field.
func MotionMimeHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldMotionMime, v))
}

// MotionMimeIsNil applies the IsNil predicate on the "motion_mime" field.
func MotionMimeIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldMotionMime))
}

// MotionMimeNotNil applies the NotNil predicate on the "motion_mime" field.
func MotionMimeNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldMotionMime))
}

// MotionMimeEqualFold applies the EqualFold predicate on the "motion_mime" field.
func MotionMimeEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldMotionMime, v))
}

// MotionMimeContainsFold applies the ContainsFold predicate on the "motion_mime" field.
func MotionMimeContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldMotionMime, v))
}

// ExifIsNil applies the IsNil predicate on the "exif" field.
func ExifIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldExif))
}

// ExifNotNil applies the NotNil predicate on the "exif" field.
func ExifNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldExif))
}

// HasTrip applies the HasEdge predicate on the "trip" edge.
func HasTrip() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TripTable, TripColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTripWith applies the HasEdge predicate on the "trip" edge with a given conditions (other predicates).
func HasTripWith(preds ...predicate.Trip) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newTripStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploadedBy applies the HasEdge predicate on the "uploaded_by" edge.
func HasUploadedBy() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UploadedByTable, UploadedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploadedByWith applies the HasEdge predicate on the "uploaded_by" edge with a given conditions (other predicates).
func HasUploadedByWith(preds ...predicate.User) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newUploadedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCollections applies the HasEdge predicate on the "collections" edge.
func HasCollections() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, CollectionsTable, CollectionsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCollectionsWith applies the HasEdge predicate on the "collections" edge with a given conditions (other predicates).
func HasCollectionsWith(preds ...predicate.Collection) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newCollectionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasViews applies the HasEdge predicate on the "views" edge.
func HasViews() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ViewsTable, ViewsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasViewsWith applies the HasEdge predicate on the "views" edge with a given conditions (other predicates).
func HasViewsWith(preds ...predicate.AssetView) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newViewsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCollectionAssets applies the HasEdge predicate on the "collection_assets" edge.
func HasCollectionAssets() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, CollectionAssetsTable, CollectionAssetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCollectionAssetsWith applies the HasEdge predicate on the "collection_assets" edge with a given conditions (other predicates).
func HasCollectionAssetsWith(preds ...predicate.CollectionAsset) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newCollectionAssetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.NotPredicates(p))
}
