// Code generated by ent, DO NOT EDIT.

package visit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloverstd/travel-moments/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUpdatedAt, v))
}

// ShareID applies equality check predicate on the "share_id" field. It's identical to ShareIDEQ.
func ShareID(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldShareID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldSessionID, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldIP, v))
}

// Ua applies equality check predicate on the "ua" field. It's identical to UaEQ.
func Ua(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUa, v))
}

// Referer applies equality check predicate on the "referer" field. It's identical to RefererEQ.
func Referer(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldReferer, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCountry, v))
}

// VisitedAt applies equality check predicate on the "visited_at" field. It's identical to VisitedAtEQ.
func VisitedAt(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldVisitedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldUpdatedAt, v))
}

// ShareIDEQ applies the EQ predicate on the "share_id" field.
func ShareIDEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldShareID, v))
}

// ShareIDNEQ applies the NEQ predicate on the "share_id" field.
func ShareIDNEQ(v int) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldShareID, v))
}

// ShareIDIn applies the In predicate on the "share_id" field.
func ShareIDIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldShareID, vs...))
}

// ShareIDNotIn applies the NotIn predicate on the "share_id" field.
func ShareIDNotIn(vs ...int) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldShareID, vs...))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldSessionID, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldIP, v))
}

// IPIsNil applies the IsNil predicate on the "ip" field.
func IPIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldIP))
}

// IPNotNil applies the NotNil predicate on the "ip" field.
func IPNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldIP))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldIP, v))
}

// UaEQ applies the EQ predicate on the "ua" field.
func UaEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldUa, v))
}

// UaNEQ applies the NEQ predicate on the "ua" field.
func UaNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldUa, v))
}

// UaIn applies the In predicate on the "ua" field.
func UaIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldUa, vs...))
}

// UaNotIn applies the NotIn predicate on the "ua" field.
func UaNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldUa, vs...))
}

// UaGT applies the GT predicate on the "ua" field.
func UaGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldUa, v))
}

// UaGTE applies the GTE predicate on the "ua" field.
func UaGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldUa, v))
}

// UaLT applies the LT predicate on the "ua" field.
func UaLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldUa, v))
}

// UaLTE applies the LTE predicate on the "ua" field.
func UaLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldUa, v))
}

// UaContains applies the Contains predicate on the "ua" field.
func UaContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldUa, v))
}

// UaHasPrefix applies the HasPrefix predicate on the "ua" field.
func UaHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldUa, v))
}

// UaHasSuffix applies the HasSuffix predicate on the "ua" field.
func UaHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldUa, v))
}

// UaIsNil applies the IsNil predicate on the "ua" field.
func UaIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldUa))
}

// UaNotNil applies the NotNil predicate on the "ua" field.
func UaNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldUa))
}

// UaEqualFold applies the EqualFold predicate on the "ua" field.
func UaEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldUa, v))
}

// UaContainsFold applies the ContainsFold predicate on the "ua" field.
func UaContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldUa, v))
}

// RefererEQ applies the EQ predicate on the "referer" field.
func RefererEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldReferer, v))
}

// RefererNEQ applies the NEQ predicate on the "referer" field.
func RefererNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldReferer, v))
}

// RefererIn applies the In predicate on the "referer" field.
func RefererIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldReferer, vs...))
}

// RefererNotIn applies the NotIn predicate on the "referer" field.
func RefererNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldReferer, vs...))
}

// RefererGT applies the GT predicate on the "referer" field.
func RefererGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldReferer, v))
}

// RefererGTE applies the GTE predicate on the "referer" field.
func RefererGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldReferer, v))
}

// RefererLT applies the LT predicate on the "referer" field.
func RefererLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldReferer, v))
}

// RefererLTE applies the LTE predicate on the "referer" field.
func RefererLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldReferer, v))
}

// RefererContains applies the Contains predicate on the "referer" field.
func RefererContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldReferer, v))
}

// RefererHasPrefix applies the HasPrefix predicate on the "referer" field.
func RefererHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldReferer, v))
}

// RefererHasSuffix applies the HasSuffix predicate on the "referer" field.
func RefererHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldReferer, v))
}

// RefererIsNil applies the IsNil predicate on the "referer" field.
func RefererIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldReferer))
}

// RefererNotNil applies the NotNil predicate on the "referer" field.
func RefererNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldReferer))
}

// RefererEqualFold applies the EqualFold predicate on the "referer" field.
func RefererEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldReferer, v))
}

// RefererContainsFold applies the ContainsFold predicate on the "referer" field.
func RefererContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldReferer, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Visit {
	return predicate.Visit(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryIsNil applies the IsNil predicate on the "country" field.
func CountryIsNil() predicate.Visit {
	return predicate.Visit(sql.FieldIsNull(FieldCountry))
}

// CountryNotNil applies the NotNil predicate on the "country" field.
func CountryNotNil() predicate.Visit {
	return predicate.Visit(sql.FieldNotNull(FieldCountry))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Visit {
	return predicate.Visit(sql.FieldContainsFold(FieldCountry, v))
}

// VisitedAtEQ applies the EQ predicate on the "visited_at" field.
func VisitedAtEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldEQ(FieldVisitedAt, v))
}

// VisitedAtNEQ applies the NEQ predicate on the "visited_at" field.
func VisitedAtNEQ(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNEQ(FieldVisitedAt, v))
}

// VisitedAtIn applies the In predicate on the "visited_at" field.
func VisitedAtIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldIn(FieldVisitedAt, vs...))
}

// VisitedAtNotIn applies the NotIn predicate on the "visited_at" field.
func VisitedAtNotIn(vs ...time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldNotIn(FieldVisitedAt, vs...))
}

// VisitedAtGT applies the GT predicate on the "visited_at" field.
func VisitedAtGT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGT(FieldVisitedAt, v))
}

// VisitedAtGTE applies the GTE predicate on the "visited_at" field.
func VisitedAtGTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldGTE(FieldVisitedAt, v))
}

// VisitedAtLT applies the LT predicate on the "visited_at" field.
func VisitedAtLT(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLT(FieldVisitedAt, v))
}

// VisitedAtLTE applies the LTE predicate on the "visited_at" field.
func VisitedAtLTE(v time.Time) predicate.Visit {
	return predicate.Visit(sql.FieldLTE(FieldVisitedAt, v))
}

// HasShare applies the HasEdge predicate on the "share" edge.
func HasShare() predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShareTable, ShareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShareWith applies the HasEdge predicate on the "share" edge with a given conditions (other predicates).
func HasShareWith(preds ...predicate.ShareLink) predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := newShareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssetViews applies the HasEdge predicate on the "asset_views" edge.
func HasAssetViews() predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetViewsTable, AssetViewsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetViewsWith applies the HasEdge predicate on the "asset_views" edge with a given conditions (other predicates).
func HasAssetViewsWith(preds ...predicate.AssetView) predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := newAssetViewsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedShares applies the HasEdge predicate on the "created_shares" edge.
func HasCreatedShares() predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CreatedSharesTable, CreatedSharesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedSharesWith applies the HasEdge predicate on the "created_shares" edge with a given conditions (other predicates).
func HasCreatedSharesWith(preds ...predicate.ShareLink) predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := newCreatedSharesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Visit {
	return predicate.Visit(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Visit) predicate.Visit {
	return predicate.Visit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Visit) predicate.Visit {
	return predicate.Visit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Visit) predicate.Visit {
	return predicate.Visit(sql.NotPredicates(p))
}
