// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/travel-moments/internal/ent/asset"
	"github.com/cloverstd/travel-moments/internal/ent/assetview"
	"github.com/cloverstd/travel-moments/internal/ent/collection"
	"github.com/cloverstd/travel-moments/internal/ent/collectionasset"
	"github.com/cloverstd/travel-moments/internal/ent/comment"
	"github.com/cloverstd/travel-moments/internal/ent/predicate"
	"github.com/cloverstd/travel-moments/internal/ent/trip"
	"github.com/cloverstd/travel-moments/internal/ent/user"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks     []Hook
	mutation  *AssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetUpdate) SetUpdatedAt(v time.Time) *AssetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTripID sets the "trip_id" field.
func (_u *AssetUpdate) SetTripID(v int) *AssetUpdate {
	_u.mutation.SetTripID(v)
	return _u
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableTripID(v *int) *AssetUpdate {
	if v != nil {
		_u.SetTripID(*v)
	}
	return _u
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (_u *AssetUpdate) SetUploadedByID(v int) *AssetUpdate {
	_u.mutation.SetUploadedByID(v)
	return _u
}

// SetNillableUploadedByID sets the "uploaded_by_id" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableUploadedByID(v *int) *AssetUpdate {
	if v != nil {
		_u.SetUploadedByID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AssetUpdate) SetKind(v asset.Kind) *AssetUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableKind(v *asset.Kind) *AssetUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetOssKey sets the "oss_key" field.
func (_u *AssetUpdate) SetOssKey(v string) *AssetUpdate {
	_u.mutation.SetOssKey(v)
	return _u
}

// SetNillableOssKey sets the "oss_key" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableOssKey(v *string) *AssetUpdate {
	if v != nil {
		_u.SetOssKey(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *AssetUpdate) SetMime(v string) *AssetUpdate {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableMime(v *string) *AssetUpdate {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// ClearMime clears the value of the "mime" field.
func (_u *AssetUpdate) ClearMime() *AssetUpdate {
	_u.mutation.ClearMime()
	return _u
}

// SetSize sets the "size" field.
func (_u *AssetUpdate) SetSize(v int64) *AssetUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableSize(v *int64) *AssetUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *AssetUpdate) AddSize(v int64) *AssetUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *AssetUpdate) SetWidth(v int) *AssetUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableWidth(v *int) *AssetUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *AssetUpdate) AddWidth(v int) *AssetUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *AssetUpdate) ClearWidth() *AssetUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *AssetUpdate) SetHeight(v int) *AssetUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableHeight(v *int) *AssetUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *AssetUpdate) AddHeight(v int) *AssetUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *AssetUpdate) ClearHeight() *AssetUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AssetUpdate) SetDurationMs(v int) *AssetUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableDurationMs(v *int) *AssetUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AssetUpdate) AddDurationMs(v int) *AssetUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AssetUpdate) ClearDurationMs() *AssetUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetTakenAt sets the "taken_at" field.
func (_u *AssetUpdate) SetTakenAt(v time.Time) *AssetUpdate {
	_u.mutation.SetTakenAt(v)
	return _u
}

// SetNillableTakenAt sets the "taken_at" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableTakenAt(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetTakenAt(*v)
	}
	return _u
}

// ClearTakenAt clears the value of the "taken_at" field.
func (_u *AssetUpdate) ClearTakenAt() *AssetUpdate {
	_u.mutation.ClearTakenAt()
	return _u
}

// SetHlsStatus sets the "hls_status" field.
func (_u *AssetUpdate) SetHlsStatus(v asset.HlsStatus) *AssetUpdate {
	_u.mutation.SetHlsStatus(v)
	return _u
}

// SetNillableHlsStatus sets the "hls_status" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableHlsStatus(v *asset.HlsStatus) *AssetUpdate {
	if v != nil {
		_u.SetHlsStatus(*v)
	}
	return _u
}

// SetHlsKey sets the "hls_key" field.
func (_u *AssetUpdate) SetHlsKey(v string) *AssetUpdate {
	_u.mutation.SetHlsKey(v)
	return _u
}

// SetNillableHlsKey sets the "hls_key" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableHlsKey(v *string) *AssetUpdate {
	if v != nil {
		_u.SetHlsKey(*v)
	}
	return _u
}

// ClearHlsKey clears the value of the "hls_key" field.
func (_u *AssetUpdate) ClearHlsKey() *AssetUpdate {
	_u.mutation.ClearHlsKey()
	return _u
}

// SetThumbKey sets the "thumb_key" field.
func (_u *AssetUpdate) SetThumbKey(v string) *AssetUpdate {
	_u.mutation.SetThumbKey(v)
	return _u
}

// SetNillableThumbKey sets the "thumb_key" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableThumbKey(v *string) *AssetUpdate {
	if v != nil {
		_u.SetThumbKey(*v)
	}
	return _u
}

// ClearThumbKey clears the value of the "thumb_key" field.
func (_u *AssetUpdate) ClearThumbKey() *AssetUpdate {
	_u.mutation.ClearThumbKey()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AssetUpdate) SetSortOrder(v int) *AssetUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableSortOrder(v *int) *AssetUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AssetUpdate) AddSortOrder(v int) *AssetUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsLivePhoto sets the "is_live_photo" field.
func (_u *AssetUpdate) SetIsLivePhoto(v bool) *AssetUpdate {
	_u.mutation.SetIsLivePhoto(v)
	return _u
}

// SetNillableIsLivePhoto sets the "is_live_photo" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableIsLivePhoto(v *bool) *AssetUpdate {
	if v != nil {
		_u.SetIsLivePhoto(*v)
	}
	return _u
}

// SetMotionKey sets the "motion_key" field.
func (_u *AssetUpdate) SetMotionKey(v string) *AssetUpdate {
	_u.mutation.SetMotionKey(v)
	return _u
}

// SetNillableMotionKey sets the "motion_key" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableMotionKey(v *string) *AssetUpdate {
	if v != nil {
		_u.SetMotionKey(*v)
	}
	return _u
}

// ClearMotionKey clears the value of the "motion_key" field.
func (_u *AssetUpdate) ClearMotionKey() *AssetUpdate {
	_u.mutation.ClearMotionKey()
	return _u
}

// SetMotionMime sets the "motion_mime" field.
func (_u *AssetUpdate) SetMotionMime(v string) *AssetUpdate {
	_u.mutation.SetMotionMime(v)
	return _u
}

// SetNillableMotionMime sets the "motion_mime" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableMotionMime(v *string) *AssetUpdate {
	if v != nil {
		_u.SetMotionMime(*v)
	}
	return _u
}

// ClearMotionMime clears the value of the "motion_mime" field.
func (_u *AssetUpdate) ClearMotionMime() *AssetUpdate {
	_u.mutation.ClearMotionMime()
	return _u
}

// SetExif sets the "exif" field.
func (_u *AssetUpdate) SetExif(v map[string]interface{}) *AssetUpdate {
	_u.mutation.SetExif(v)
	return _u
}

// ClearExif clears the value of the "exif" field.
func (_u *AssetUpdate) ClearExif() *AssetUpdate {
	_u.mutation.ClearExif()
	return _u
}

// SetTrip sets the "trip" edge to the Trip entity.
func (_u *AssetUpdate) SetTrip(v *Trip) *AssetUpdate {
	return _u.SetTripID(v.ID)
}

// SetUploadedBy sets the "uploaded_by" edge to the User entity.
func (_u *AssetUpdate) SetUploadedBy(v *User) *AssetUpdate {
	return _u.SetUploadedByID(v.ID)
}

// AddCollectionIDs adds the "collections" edge to the Collection entity by IDs.
func (_u *AssetUpdate) AddCollectionIDs(ids ...int) *AssetUpdate {
	_u.mutation.AddCollectionIDs(ids...)
	return _u
}

// AddCollections adds the "collections" edges to the Collection entity.
func (_u *AssetUpdate) AddCollections(v ...*Collection) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionIDs(ids...)
}

// AddViewIDs adds the "views" edge to the AssetView entity by IDs.
func (_u *AssetUpdate) AddViewIDs(ids ...int) *AssetUpdate {
	_u.mutation.AddViewIDs(ids...)
	return _u
}

// AddViews adds the "views" edges to the AssetView entity.
func (_u *AssetUpdate) AddViews(v ...*AssetView) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddViewIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *AssetUpdate) AddCommentIDs(ids ...int) *AssetUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *AssetUpdate) AddComments(v ...*Comment) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddCollectionAssetIDs adds the "collection_assets" edge to the CollectionAsset entity by IDs.
func (_u *AssetUpdate) AddCollectionAssetIDs(ids ...int) *AssetUpdate {
	_u.mutation.AddCollectionAssetIDs(ids...)
	return _u
}

// AddCollectionAssets adds the "collection_assets" edges to the CollectionAsset entity.
func (_u *AssetUpdate) AddCollectionAssets(v ...*CollectionAsset) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionAssetIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTrip clears the "trip" edge to the Trip entity.
func (_u *AssetUpdate) ClearTrip() *AssetUpdate {
	_u.mutation.ClearTrip()
	return _u
}

// ClearUploadedBy clears the "uploaded_by" edge to the User entity.
func (_u *AssetUpdate) ClearUploadedBy() *AssetUpdate {
	_u.mutation.ClearUploadedBy()
	return _u
}

// ClearCollections clears all "collections" edges to the Collection entity.
func (_u *AssetUpdate) ClearCollections() *AssetUpdate {
	_u.mutation.ClearCollections()
	return _u
}

// RemoveCollectionIDs removes the "collections" edge to Collection entities by IDs.
func (_u *AssetUpdate) RemoveCollectionIDs(ids ...int) *AssetUpdate {
	_u.mutation.RemoveCollectionIDs(ids...)
	return _u
}

// RemoveCollections removes "collections" edges to Collection entities.
func (_u *AssetUpdate) RemoveCollections(v ...*Collection) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionIDs(ids...)
}

// ClearViews clears all "views" edges to the AssetView entity.
func (_u *AssetUpdate) ClearViews() *AssetUpdate {
	_u.mutation.ClearViews()
	return _u
}

// RemoveViewIDs removes the "views" edge to AssetView entities by IDs.
func (_u *AssetUpdate) RemoveViewIDs(ids ...int) *AssetUpdate {
	_u.mutation.RemoveViewIDs(ids...)
	return _u
}

// RemoveViews removes "views" edges to AssetView entities.
func (_u *AssetUpdate) RemoveViews(v ...*AssetView) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveViewIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *AssetUpdate) ClearComments() *AssetUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *AssetUpdate) RemoveCommentIDs(ids ...int) *AssetUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *AssetUpdate) RemoveComments(v ...*Comment) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearCollectionAssets clears all "collection_assets" edges to the CollectionAsset entity.
func (_u *AssetUpdate) ClearCollectionAssets() *AssetUpdate {
	_u.mutation.ClearCollectionAssets()
	return _u
}

// RemoveCollectionAssetIDs removes the "collection_assets" edge to CollectionAsset entities by IDs.
func (_u *AssetUpdate) RemoveCollectionAssetIDs(ids ...int) *AssetUpdate {
	_u.mutation.RemoveCollectionAssetIDs(ids...)
	return _u
}

// RemoveCollectionAssets removes "collection_assets" edges to CollectionAsset entities.
func (_u *AssetUpdate) RemoveCollectionAssets(v ...*CollectionAsset) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionAssetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := asset.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Asset.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OssKey(); ok {
		if err := asset.OssKeyValidator(v); err != nil {
			return &ValidationError{Name: "oss_key", err: fmt.Errorf(`ent: validator failed for field "Asset.oss_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HlsStatus(); ok {
		if err := asset.HlsStatusValidator(v); err != nil {
			return &ValidationError{Name: "hls_status", err: fmt.Errorf(`ent: validator failed for field "Asset.hls_status": %w`, err)}
		}
	}
	if _u.mutation.TripCleared() && len(_u.mutation.TripIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.trip"`)
	}
	if _u.mutation.UploadedByCleared() && len(_u.mutation.UploadedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.uploaded_by"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AssetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AssetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(asset.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OssKey(); ok {
		_spec.SetField(asset.FieldOssKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(asset.FieldMime, field.TypeString, value)
	}
	if _u.mutation.MimeCleared() {
		_spec.ClearField(asset.FieldMime, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(asset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(asset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(asset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(asset.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(asset.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(asset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(asset.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(asset.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(asset.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(asset.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(asset.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.TakenAt(); ok {
		_spec.SetField(asset.FieldTakenAt, field.TypeTime, value)
	}
	if _u.mutation.TakenAtCleared() {
		_spec.ClearField(asset.FieldTakenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HlsStatus(); ok {
		_spec.SetField(asset.FieldHlsStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HlsKey(); ok {
		_spec.SetField(asset.FieldHlsKey, field.TypeString, value)
	}
	if _u.mutation.HlsKeyCleared() {
		_spec.ClearField(asset.FieldHlsKey, field.TypeString)
	}
	if value, ok := _u.mutation.ThumbKey(); ok {
		_spec.SetField(asset.FieldThumbKey, field.TypeString, value)
	}
	if _u.mutation.ThumbKeyCleared() {
		_spec.ClearField(asset.FieldThumbKey, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(asset.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(asset.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsLivePhoto(); ok {
		_spec.SetField(asset.FieldIsLivePhoto, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MotionKey(); ok {
		_spec.SetField(asset.FieldMotionKey, field.TypeString, value)
	}
	if _u.mutation.MotionKeyCleared() {
		_spec.ClearField(asset.FieldMotionKey, field.TypeString)
	}
	if value, ok := _u.mutation.MotionMime(); ok {
		_spec.SetField(asset.FieldMotionMime, field.TypeString, value)
	}
	if _u.mutation.MotionMimeCleared() {
		_spec.ClearField(asset.FieldMotionMime, field.TypeString)
	}
	if value, ok := _u.mutation.Exif(); ok {
		_spec.SetField(asset.FieldExif, field.TypeJSON, value)
	}
	if _u.mutation.ExifCleared() {
		_spec.ClearField(asset.FieldExif, field.TypeJSON)
	}
	if _u.mutation.TripCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TripTable,
			Columns: []string{asset.TripColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TripIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TripTable,
			Columns: []string{asset.TripColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploadedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.UploadedByTable,
			Columns: []string{asset.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.UploadedByTable,
			Columns: []string{asset.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		createE := &CollectionAssetCreate{config: _u.config, mutation: newCollectionAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionsIDs(); len(nodes) > 0 && !_u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CollectionAssetCreate{config: _u.config, mutation: newCollectionAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CollectionAssetCreate{config: _u.config, mutation: newCollectionAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedViewsIDs(); len(nodes) > 0 && !_u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionAssetsIDs(); len(nodes) > 0 && !_u.mutation.CollectionAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AssetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetUpdateOne) SetUpdatedAt(v time.Time) *AssetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTripID sets the "trip_id" field.
func (_u *AssetUpdateOne) SetTripID(v int) *AssetUpdateOne {
	_u.mutation.SetTripID(v)
	return _u
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableTripID(v *int) *AssetUpdateOne {
	if v != nil {
		_u.SetTripID(*v)
	}
	return _u
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (_u *AssetUpdateOne) SetUploadedByID(v int) *AssetUpdateOne {
	_u.mutation.SetUploadedByID(v)
	return _u
}

// SetNillableUploadedByID sets the "uploaded_by_id" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableUploadedByID(v *int) *AssetUpdateOne {
	if v != nil {
		_u.SetUploadedByID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AssetUpdateOne) SetKind(v asset.Kind) *AssetUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableKind(v *asset.Kind) *AssetUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetOssKey sets the "oss_key" field.
func (_u *AssetUpdateOne) SetOssKey(v string) *AssetUpdateOne {
	_u.mutation.SetOssKey(v)
	return _u
}

// SetNillableOssKey sets the "oss_key" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableOssKey(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetOssKey(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *AssetUpdateOne) SetMime(v string) *AssetUpdateOne {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableMime(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// ClearMime clears the value of the "mime" field.
func (_u *AssetUpdateOne) ClearMime() *AssetUpdateOne {
	_u.mutation.ClearMime()
	return _u
}

// SetSize sets the "size" field.
func (_u *AssetUpdateOne) SetSize(v int64) *AssetUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableSize(v *int64) *AssetUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *AssetUpdateOne) AddSize(v int64) *AssetUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *AssetUpdateOne) SetWidth(v int) *AssetUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableWidth(v *int) *AssetUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *AssetUpdateOne) AddWidth(v int) *AssetUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *AssetUpdateOne) ClearWidth() *AssetUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *AssetUpdateOne) SetHeight(v int) *AssetUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableHeight(v *int) *AssetUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *AssetUpdateOne) AddHeight(v int) *AssetUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *AssetUpdateOne) ClearHeight() *AssetUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AssetUpdateOne) SetDurationMs(v int) *AssetUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableDurationMs(v *int) *AssetUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AssetUpdateOne) AddDurationMs(v int) *AssetUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AssetUpdateOne) ClearDurationMs() *AssetUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetTakenAt sets the "taken_at" field.
func (_u *AssetUpdateOne) SetTakenAt(v time.Time) *AssetUpdateOne {
	_u.mutation.SetTakenAt(v)
	return _u
}

// SetNillableTakenAt sets the "taken_at" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableTakenAt(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetTakenAt(*v)
	}
	return _u
}

// ClearTakenAt clears the value of the "taken_at" field.
func (_u *AssetUpdateOne) ClearTakenAt() *AssetUpdateOne {
	_u.mutation.ClearTakenAt()
	return _u
}

// SetHlsStatus sets the "hls_status" field.
func (_u *AssetUpdateOne) SetHlsStatus(v asset.HlsStatus) *AssetUpdateOne {
	_u.mutation.SetHlsStatus(v)
	return _u
}

// SetNillableHlsStatus sets the "hls_status" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableHlsStatus(v *asset.HlsStatus) *AssetUpdateOne {
	if v != nil {
		_u.SetHlsStatus(*v)
	}
	return _u
}

// SetHlsKey sets the "hls_key" field.
func (_u *AssetUpdateOne) SetHlsKey(v string) *AssetUpdateOne {
	_u.mutation.SetHlsKey(v)
	return _u
}

// SetNillableHlsKey sets the "hls_key" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableHlsKey(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetHlsKey(*v)
	}
	return _u
}

// ClearHlsKey clears the value of the "hls_key" field.
func (_u *AssetUpdateOne) ClearHlsKey() *AssetUpdateOne {
	_u.mutation.ClearHlsKey()
	return _u
}

// SetThumbKey sets the "thumb_key" field.
func (_u *AssetUpdateOne) SetThumbKey(v string) *AssetUpdateOne {
	_u.mutation.SetThumbKey(v)
	return _u
}

// SetNillableThumbKey sets the "thumb_key" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableThumbKey(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetThumbKey(*v)
	}
	return _u
}

// ClearThumbKey clears the value of the "thumb_key" field.
func (_u *AssetUpdateOne) ClearThumbKey() *AssetUpdateOne {
	_u.mutation.ClearThumbKey()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AssetUpdateOne) SetSortOrder(v int) *AssetUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableSortOrder(v *int) *AssetUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AssetUpdateOne) AddSortOrder(v int) *AssetUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsLivePhoto sets the "is_live_photo" field.
func (_u *AssetUpdateOne) SetIsLivePhoto(v bool) *AssetUpdateOne {
	_u.mutation.SetIsLivePhoto(v)
	return _u
}

// SetNillableIsLivePhoto sets the "is_live_photo" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableIsLivePhoto(v *bool) *AssetUpdateOne {
	if v != nil {
		_u.SetIsLivePhoto(*v)
	}
	return _u
}

// SetMotionKey sets the "motion_key" field.
func (_u *AssetUpdateOne) SetMotionKey(v string) *AssetUpdateOne {
	_u.mutation.SetMotionKey(v)
	return _u
}

// SetNillableMotionKey sets the "motion_key" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableMotionKey(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetMotionKey(*v)
	}
	return _u
}

// ClearMotionKey clears the value of the "motion_key" field.
func (_u *AssetUpdateOne) ClearMotionKey() *AssetUpdateOne {
	_u.mutation.ClearMotionKey()
	return _u
}

// SetMotionMime sets the "motion_mime" field.
func (_u *AssetUpdateOne) SetMotionMime(v string) *AssetUpdateOne {
	_u.mutation.SetMotionMime(v)
	return _u
}

// SetNillableMotionMime sets the "motion_mime" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableMotionMime(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetMotionMime(*v)
	}
	return _u
}

// ClearMotionMime clears the value of the "motion_mime" field.
func (_u *AssetUpdateOne) ClearMotionMime() *AssetUpdateOne {
	_u.mutation.ClearMotionMime()
	return _u
}

// SetExif sets the "exif" field.
func (_u *AssetUpdateOne) SetExif(v map[string]interface{}) *AssetUpdateOne {
	_u.mutation.SetExif(v)
	return _u
}

// ClearExif clears the value of the "exif" field.
func (_u *AssetUpdateOne) ClearExif() *AssetUpdateOne {
	_u.mutation.ClearExif()
	return _u
}

// SetTrip sets the "trip" edge to the Trip entity.
func (_u *AssetUpdateOne) SetTrip(v *Trip) *AssetUpdateOne {
	return _u.SetTripID(v.ID)
}

// SetUploadedBy sets the "uploaded_by" edge to the User entity.
func (_u *AssetUpdateOne) SetUploadedBy(v *User) *AssetUpdateOne {
	return _u.SetUploadedByID(v.ID)
}

// AddCollectionIDs adds the "collections" edge to the Collection entity by IDs.
func (_u *AssetUpdateOne) AddCollectionIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.AddCollectionIDs(ids...)
	return _u
}

// AddCollections adds the "collections" edges to the Collection entity.
func (_u *AssetUpdateOne) AddCollections(v ...*Collection) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionIDs(ids...)
}

// AddViewIDs adds the "views" edge to the AssetView entity by IDs.
func (_u *AssetUpdateOne) AddViewIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.AddViewIDs(ids...)
	return _u
}

// AddViews adds the "views" edges to the AssetView entity.
func (_u *AssetUpdateOne) AddViews(v ...*AssetView) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddViewIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *AssetUpdateOne) AddCommentIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *AssetUpdateOne) AddComments(v ...*Comment) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddCollectionAssetIDs adds the "collection_assets" edge to the CollectionAsset entity by IDs.
func (_u *AssetUpdateOne) AddCollectionAssetIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.AddCollectionAssetIDs(ids...)
	return _u
}

// AddCollectionAssets adds the "collection_assets" edges to the CollectionAsset entity.
func (_u *AssetUpdateOne) AddCollectionAssets(v ...*CollectionAsset) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionAssetIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTrip clears the "trip" edge to the Trip entity.
func (_u *AssetUpdateOne) ClearTrip() *AssetUpdateOne {
	_u.mutation.ClearTrip()
	return _u
}

// ClearUploadedBy clears the "uploaded_by" edge to the User entity.
func (_u *AssetUpdateOne) ClearUploadedBy() *AssetUpdateOne {
	_u.mutation.ClearUploadedBy()
	return _u
}

// ClearCollections clears all "collections" edges to the Collection entity.
func (_u *AssetUpdateOne) ClearCollections() *AssetUpdateOne {
	_u.mutation.ClearCollections()
	return _u
}

// RemoveCollectionIDs removes the "collections" edge to Collection entities by IDs.
func (_u *AssetUpdateOne) RemoveCollectionIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.RemoveCollectionIDs(ids...)
	return _u
}

// RemoveCollections removes "collections" edges to Collection entities.
func (_u *AssetUpdateOne) RemoveCollections(v ...*Collection) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionIDs(ids...)
}

// ClearViews clears all "views" edges to the AssetView entity.
func (_u *AssetUpdateOne) ClearViews() *AssetUpdateOne {
	_u.mutation.ClearViews()
	return _u
}

// RemoveViewIDs removes the "views" edge to AssetView entities by IDs.
func (_u *AssetUpdateOne) RemoveViewIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.RemoveViewIDs(ids...)
	return _u
}

// RemoveViews removes "views" edges to AssetView entities.
func (_u *AssetUpdateOne) RemoveViews(v ...*AssetView) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveViewIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *AssetUpdateOne) ClearComments() *AssetUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *AssetUpdateOne) RemoveCommentIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *AssetUpdateOne) RemoveComments(v ...*Comment) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearCollectionAssets clears all "collection_assets" edges to the CollectionAsset entity.
func (_u *AssetUpdateOne) ClearCollectionAssets() *AssetUpdateOne {
	_u.mutation.ClearCollectionAssets()
	return _u
}

// RemoveCollectionAssetIDs removes the "collection_assets" edge to CollectionAsset entities by IDs.
func (_u *AssetUpdateOne) RemoveCollectionAssetIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.RemoveCollectionAssetIDs(ids...)
	return _u
}

// RemoveCollectionAssets removes "collection_assets" edges to CollectionAsset entities.
func (_u *AssetUpdateOne) RemoveCollectionAssets(v ...*CollectionAsset) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionAssetIDs(ids...)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := asset.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Asset.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OssKey(); ok {
		if err := asset.OssKeyValidator(v); err != nil {
			return &ValidationError{Name: "oss_key", err: fmt.Errorf(`ent: validator failed for field "Asset.oss_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HlsStatus(); ok {
		if err := asset.HlsStatusValidator(v); err != nil {
			return &ValidationError{Name: "hls_status", err: fmt.Errorf(`ent: validator failed for field "Asset.hls_status": %w`, err)}
		}
	}
	if _u.mutation.TripCleared() && len(_u.mutation.TripIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.trip"`)
	}
	if _u.mutation.UploadedByCleared() && len(_u.mutation.UploadedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Asset.uploaded_by"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AssetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AssetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(asset.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OssKey(); ok {
		_spec.SetField(asset.FieldOssKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(asset.FieldMime, field.TypeString, value)
	}
	if _u.mutation.MimeCleared() {
		_spec.ClearField(asset.FieldMime, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(asset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(asset.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(asset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(asset.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(asset.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(asset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(asset.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(asset.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(asset.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(asset.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(asset.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.TakenAt(); ok {
		_spec.SetField(asset.FieldTakenAt, field.TypeTime, value)
	}
	if _u.mutation.TakenAtCleared() {
		_spec.ClearField(asset.FieldTakenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HlsStatus(); ok {
		_spec.SetField(asset.FieldHlsStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HlsKey(); ok {
		_spec.SetField(asset.FieldHlsKey, field.TypeString, value)
	}
	if _u.mutation.HlsKeyCleared() {
		_spec.ClearField(asset.FieldHlsKey, field.TypeString)
	}
	if value, ok := _u.mutation.ThumbKey(); ok {
		_spec.SetField(asset.FieldThumbKey, field.TypeString, value)
	}
	if _u.mutation.ThumbKeyCleared() {
		_spec.ClearField(asset.FieldThumbKey, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(asset.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(asset.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsLivePhoto(); ok {
		_spec.SetField(asset.FieldIsLivePhoto, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MotionKey(); ok {
		_spec.SetField(asset.FieldMotionKey, field.TypeString, value)
	}
	if _u.mutation.MotionKeyCleared() {
		_spec.ClearField(asset.FieldMotionKey, field.TypeString)
	}
	if value, ok := _u.mutation.MotionMime(); ok {
		_spec.SetField(asset.FieldMotionMime, field.TypeString, value)
	}
	if _u.mutation.MotionMimeCleared() {
		_spec.ClearField(asset.FieldMotionMime, field.TypeString)
	}
	if value, ok := _u.mutation.Exif(); ok {
		_spec.SetField(asset.FieldExif, field.TypeJSON, value)
	}
	if _u.mutation.ExifCleared() {
		_spec.ClearField(asset.FieldExif, field.TypeJSON)
	}
	if _u.mutation.TripCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TripTable,
			Columns: []string{asset.TripColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TripIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TripTable,
			Columns: []string{asset.TripColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploadedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.UploadedByTable,
			Columns: []string{asset.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.UploadedByTable,
			Columns: []string{asset.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		createE := &CollectionAssetCreate{config: _u.config, mutation: newCollectionAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionsIDs(); len(nodes) > 0 && !_u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CollectionAssetCreate{config: _u.config, mutation: newCollectionAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CollectionAssetCreate{config: _u.config, mutation: newCollectionAssetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedViewsIDs(); len(nodes) > 0 && !_u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionAssetsIDs(); len(nodes) > 0 && !_u.mutation.CollectionAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
