// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/travel-moments/internal/ent/asset"
	"github.com/cloverstd/travel-moments/internal/ent/assetview"
	"github.com/cloverstd/travel-moments/internal/ent/collection"
	"github.com/cloverstd/travel-moments/internal/ent/collectionasset"
	"github.com/cloverstd/travel-moments/internal/ent/comment"
	"github.com/cloverstd/travel-moments/internal/ent/trip"
	"github.com/cloverstd/travel-moments/internal/ent/user"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AssetCreate) SetCreatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableCreatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AssetCreate) SetUpdatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableUpdatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTripID sets the "trip_id" field.
func (_c *AssetCreate) SetTripID(v int) *AssetCreate {
	_c.mutation.SetTripID(v)
	return _c
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (_c *AssetCreate) SetUploadedByID(v int) *AssetCreate {
	_c.mutation.SetUploadedByID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *AssetCreate) SetKind(v asset.Kind) *AssetCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetOssKey sets the "oss_key" field.
func (_c *AssetCreate) SetOssKey(v string) *AssetCreate {
	_c.mutation.SetOssKey(v)
	return _c
}

// SetMime sets the "mime" field.
func (_c *AssetCreate) SetMime(v string) *AssetCreate {
	_c.mutation.SetMime(v)
	return _c
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_c *AssetCreate) SetNillableMime(v *string) *AssetCreate {
	if v != nil {
		_c.SetMime(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *AssetCreate) SetSize(v int64) *AssetCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *AssetCreate) SetNillableSize(v *int64) *AssetCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *AssetCreate) SetWidth(v int) *AssetCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *AssetCreate) SetNillableWidth(v *int) *AssetCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *AssetCreate) SetHeight(v int) *AssetCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *AssetCreate) SetNillableHeight(v *int) *AssetCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AssetCreate) SetDurationMs(v int) *AssetCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AssetCreate) SetNillableDurationMs(v *int) *AssetCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetTakenAt sets the "taken_at" field.
func (_c *AssetCreate) SetTakenAt(v time.Time) *AssetCreate {
	_c.mutation.SetTakenAt(v)
	return _c
}

// SetNillableTakenAt sets the "taken_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableTakenAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetTakenAt(*v)
	}
	return _c
}

// SetHlsStatus sets the "hls_status" field.
func (_c *AssetCreate) SetHlsStatus(v asset.HlsStatus) *AssetCreate {
	_c.mutation.SetHlsStatus(v)
	return _c
}

// SetNillableHlsStatus sets the "hls_status" field if the given value is not nil.
func (_c *AssetCreate) SetNillableHlsStatus(v *asset.HlsStatus) *AssetCreate {
	if v != nil {
		_c.SetHlsStatus(*v)
	}
	return _c
}

// SetHlsKey sets the "hls_key" field.
func (_c *AssetCreate) SetHlsKey(v string) *AssetCreate {
	_c.mutation.SetHlsKey(v)
	return _c
}

// SetNillableHlsKey sets the "hls_key" field if the given value is not nil.
func (_c *AssetCreate) SetNillableHlsKey(v *string) *AssetCreate {
	if v != nil {
		_c.SetHlsKey(*v)
	}
	return _c
}

// SetThumbKey sets the "thumb_key" field.
func (_c *AssetCreate) SetThumbKey(v string) *AssetCreate {
	_c.mutation.SetThumbKey(v)
	return _c
}

// SetNillableThumbKey sets the "thumb_key" field if the given value is not nil.
func (_c *AssetCreate) SetNillableThumbKey(v *string) *AssetCreate {
	if v != nil {
		_c.SetThumbKey(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AssetCreate) SetSortOrder(v int) *AssetCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AssetCreate) SetNillableSortOrder(v *int) *AssetCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsLivePhoto sets the "is_live_photo" field.
func (_c *AssetCreate) SetIsLivePhoto(v bool) *AssetCreate {
	_c.mutation.SetIsLivePhoto(v)
	return _c
}

// SetNillableIsLivePhoto sets the "is_live_photo" field if the given value is not nil.
func (_c *AssetCreate) SetNillableIsLivePhoto(v *bool) *AssetCreate {
	if v != nil {
		_c.SetIsLivePhoto(*v)
	}
	return _c
}

// SetMotionKey sets the "motion_key" field.
func (_c *AssetCreate) SetMotionKey(v string) *AssetCreate {
	_c.mutation.SetMotionKey(v)
	return _c
}

// SetNillableMotionKey sets the "motion_key" field if the given value is not nil.
func (_c *AssetCreate) SetNillableMotionKey(v *string) *AssetCreate {
	if v != nil {
		_c.SetMotionKey(*v)
	}
	return _c
}

// SetMotionMime sets the "motion_mime" field.
func (_c *AssetCreate) SetMotionMime(v string) *AssetCreate {
	_c.mutation.SetMotionMime(v)
	return _c
}

// SetNillableMotionMime sets the "motion_mime" field if the given value is not nil.
func (_c *AssetCreate) SetNillableMotionMime(v *string) *AssetCreate {
	if v != nil {
		_c.SetMotionMime(*v)
	}
	return _c
}

// SetExif sets the "exif" field.
func (_c *AssetCreate) SetExif(v map[string]interface{}) *AssetCreate {
	_c.mutation.SetExif(v)
	return _c
}

// SetTrip sets the "trip" edge to the Trip entity.
func (_c *AssetCreate) SetTrip(v *Trip) *AssetCreate {
	return _c.SetTripID(v.ID)
}

// SetUploadedBy sets the "uploaded_by" edge to the User entity.
func (_c *AssetCreate) SetUploadedBy(v *User) *AssetCreate {
	return _c.SetUploadedByID(v.ID)
}

// AddCollectionIDs adds the "collections" edge to the Collection entity by IDs.
func (_c *AssetCreate) AddCollectionIDs(ids ...int) *AssetCreate {
	_c.mutation.AddCollectionIDs(ids...)
	return _c
}

// AddCollections adds the "collections" edges to the Collection entity.
func (_c *AssetCreate) AddCollections(v ...*Collection) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCollectionIDs(ids...)
}

// AddViewIDs adds the "views" edge to the AssetView entity by IDs.
func (_c *AssetCreate) AddViewIDs(ids ...int) *AssetCreate {
	_c.mutation.AddViewIDs(ids...)
	return _c
}

// AddViews adds the "views" edges to the AssetView entity.
func (_c *AssetCreate) AddViews(v ...*AssetView) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddViewIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_c *AssetCreate) AddCommentIDs(ids ...int) *AssetCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the Comment entity.
func (_c *AssetCreate) AddComments(v ...*Comment) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// AddCollectionAssetIDs adds the "collection_assets" edge to the CollectionAsset entity by IDs.
func (_c *AssetCreate) AddCollectionAssetIDs(ids ...int) *AssetCreate {
	_c.mutation.AddCollectionAssetIDs(ids...)
	return _c
}

// AddCollectionAssets adds the "collection_assets" edges to the CollectionAsset entity.
func (_c *AssetCreate) AddCollectionAssets(v ...*CollectionAsset) *AssetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCollectionAssetIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_c *AssetCreate) Mutation() *AssetMutation {
	return _c.mutation
}

// Save creates the Asset in the database.
func (_c *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := asset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := asset.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := asset.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.HlsStatus(); !ok {
		v := asset.DefaultHlsStatus
		_c.mutation.SetHlsStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := asset.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsLivePhoto(); !ok {
		v := asset.DefaultIsLivePhoto
		_c.mutation.SetIsLivePhoto(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Asset.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Asset.updated_at"`)}
	}
	if _, ok := _c.mutation.TripID(); !ok {
		return &ValidationError{Name: "trip_id", err: errors.New(`ent: missing required field "Asset.trip_id"`)}
	}
	if _, ok := _c.mutation.UploadedByID(); !ok {
		return &ValidationError{Name: "uploaded_by_id", err: errors.New(`ent: missing required field "Asset.uploaded_by_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Asset.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := asset.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Asset.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OssKey(); !ok {
		return &ValidationError{Name: "oss_key", err: errors.New(`ent: missing required field "Asset.oss_key"`)}
	}
	if v, ok := _c.mutation.OssKey(); ok {
		if err := asset.OssKeyValidator(v); err != nil {
			return &ValidationError{Name: "oss_key", err: fmt.Errorf(`ent: validator failed for field "Asset.oss_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Asset.size"`)}
	}
	if _, ok := _c.mutation.HlsStatus(); !ok {
		return &ValidationError{Name: "hls_status", err: errors.New(`ent: missing required field "Asset.hls_status"`)}
	}
	if v, ok := _c.mutation.HlsStatus(); ok {
		if err := asset.HlsStatusValidator(v); err != nil {
			return &ValidationError{Name: "hls_status", err: fmt.Errorf(`ent: validator failed for field "Asset.hls_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Asset.sort_order"`)}
	}
	if _, ok := _c.mutation.IsLivePhoto(); !ok {
		return &ValidationError{Name: "is_live_photo", err: errors.New(`ent: missing required field "Asset.is_live_photo"`)}
	}
	if len(_c.mutation.TripIDs()) == 0 {
		return &ValidationError{Name: "trip", err: errors.New(`ent: missing required edge "Asset.trip"`)}
	}
	if len(_c.mutation.UploadedByIDs()) == 0 {
		return &ValidationError{Name: "uploaded_by", err: errors.New(`ent: missing required edge "Asset.uploaded_by"`)}
	}
	return nil
}

func (_c *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(asset.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.OssKey(); ok {
		_spec.SetField(asset.FieldOssKey, field.TypeString, value)
		_node.OssKey = value
	}
	if value, ok := _c.mutation.Mime(); ok {
		_spec.SetField(asset.FieldMime, field.TypeString, value)
		_node.Mime = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(asset.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(asset.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(asset.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(asset.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.TakenAt(); ok {
		_spec.SetField(asset.FieldTakenAt, field.TypeTime, value)
		_node.TakenAt = &value
	}
	if value, ok := _c.mutation.HlsStatus(); ok {
		_spec.SetField(asset.FieldHlsStatus, field.TypeEnum, value)
		_node.HlsStatus = value
	}
	if value, ok := _c.mutation.HlsKey(); ok {
		_spec.SetField(asset.FieldHlsKey, field.TypeString, value)
		_node.HlsKey = value
	}
	if value, ok := _c.mutation.ThumbKey(); ok {
		_spec.SetField(asset.FieldThumbKey, field.TypeString, value)
		_node.ThumbKey = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(asset.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.IsLivePhoto(); ok {
		_spec.SetField(asset.FieldIsLivePhoto, field.TypeBool, value)
		_node.IsLivePhoto = value
	}
	if value, ok := _c.mutation.MotionKey(); ok {
		_spec.SetField(asset.FieldMotionKey, field.TypeString, value)
		_node.MotionKey = value
	}
	if value, ok := _c.mutation.MotionMime(); ok {
		_spec.SetField(asset.FieldMotionMime, field.TypeString, value)
		_node.MotionMime = value
	}
	if value, ok := _c.mutation.Exif(); ok {
		_spec.SetField(asset.FieldExif, field.TypeJSON, value)
		_node.Exif = value
	}
	if nodes := _c.mutation.TripIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.TripTable,
			Columns: []string{asset.TripColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TripID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UploadedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asset.UploadedByTable,
			Columns: []string{asset.UploadedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploadedByID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.CollectionsTable,
			Columns: asset.CollectionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CollectionAssetCreate{config: _c.config, mutation: newCollectionAssetMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.ViewsTable,
			Columns: []string{asset.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CommentsTable,
			Columns: []string{asset.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CollectionAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   asset.CollectionAssetsTable,
			Columns: []string{asset.CollectionAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectionasset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Asset.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetCreate) OnConflict(opts ...sql.ConflictOption) *AssetUpsertOne {
	_c.conflict = opts
	return &AssetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetCreate) OnConflictColumns(columns ...string) *AssetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetUpsertOne{
		create: _c,
	}
}

type (
	// AssetUpsertOne is the builder for "upsert"-ing
	//  one Asset node.
	AssetUpsertOne struct {
		create *AssetCreate
	}

	// AssetUpsert is the "OnConflict" setter.
	AssetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsert) SetUpdatedAt(v time.Time) *AssetUpsert {
	u.Set(asset.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsert) UpdateUpdatedAt() *AssetUpsert {
	u.SetExcluded(asset.FieldUpdatedAt)
	return u
}

// SetTripID sets the "trip_id" field.
func (u *AssetUpsert) SetTripID(v int) *AssetUpsert {
	u.Set(asset.FieldTripID, v)
	return u
}

// UpdateTripID sets the "trip_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateTripID() *AssetUpsert {
	u.SetExcluded(asset.FieldTripID)
	return u
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (u *AssetUpsert) SetUploadedByID(v int) *AssetUpsert {
	u.Set(asset.FieldUploadedByID, v)
	return u
}

// UpdateUploadedByID sets the "uploaded_by_id" field to the value that was provided on create.
func (u *AssetUpsert) UpdateUploadedByID() *AssetUpsert {
	u.SetExcluded(asset.FieldUploadedByID)
	return u
}

// SetKind sets the "kind" field.
func (u *AssetUpsert) SetKind(v asset.Kind) *AssetUpsert {
	u.Set(asset.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AssetUpsert) UpdateKind() *AssetUpsert {
	u.SetExcluded(asset.FieldKind)
	return u
}

// SetOssKey sets the "oss_key" field.
func (u *AssetUpsert) SetOssKey(v string) *AssetUpsert {
	u.Set(asset.FieldOssKey, v)
	return u
}

// UpdateOssKey sets the "oss_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateOssKey() *AssetUpsert {
	u.SetExcluded(asset.FieldOssKey)
	return u
}

// SetMime sets the "mime" field.
func (u *AssetUpsert) SetMime(v string) *AssetUpsert {
	u.Set(asset.FieldMime, v)
	return u
}

// UpdateMime sets the "mime" field to the value that was provided on create.
func (u *AssetUpsert) UpdateMime() *AssetUpsert {
	u.SetExcluded(asset.FieldMime)
	return u
}

// ClearMime clears the value of the "mime" field.
func (u *AssetUpsert) ClearMime() *AssetUpsert {
	u.SetNull(asset.FieldMime)
	return u
}

// SetSize sets the "size" field.
func (u *AssetUpsert) SetSize(v int64) *AssetUpsert {
	u.Set(asset.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *AssetUpsert) UpdateSize() *AssetUpsert {
	u.SetExcluded(asset.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *AssetUpsert) AddSize(v int64) *AssetUpsert {
	u.Add(asset.FieldSize, v)
	return u
}

// SetWidth sets the "width" field.
func (u *AssetUpsert) SetWidth(v int) *AssetUpsert {
	u.Set(asset.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *AssetUpsert) UpdateWidth() *AssetUpsert {
	u.SetExcluded(asset.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *AssetUpsert) AddWidth(v int) *AssetUpsert {
	u.Add(asset.FieldWidth, v)
	return u
}

// ClearWidth clears the value of the "width" field.
func (u *AssetUpsert) ClearWidth() *AssetUpsert {
	u.SetNull(asset.FieldWidth)
	return u
}

// SetHeight sets the "height" field.
func (u *AssetUpsert) SetHeight(v int) *AssetUpsert {
	u.Set(asset.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *AssetUpsert) UpdateHeight() *AssetUpsert {
	u.SetExcluded(asset.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *AssetUpsert) AddHeight(v int) *AssetUpsert {
	u.Add(asset.FieldHeight, v)
	return u
}

// ClearHeight clears the value of the "height" field.
func (u *AssetUpsert) ClearHeight() *AssetUpsert {
	u.SetNull(asset.FieldHeight)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *AssetUpsert) SetDurationMs(v int) *AssetUpsert {
	u.Set(asset.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AssetUpsert) UpdateDurationMs() *AssetUpsert {
	u.SetExcluded(asset.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AssetUpsert) AddDurationMs(v int) *AssetUpsert {
	u.Add(asset.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AssetUpsert) ClearDurationMs() *AssetUpsert {
	u.SetNull(asset.FieldDurationMs)
	return u
}

// SetTakenAt sets the "taken_at" field.
func (u *AssetUpsert) SetTakenAt(v time.Time) *AssetUpsert {
	u.Set(asset.FieldTakenAt, v)
	return u
}

// UpdateTakenAt sets the "taken_at" field to the value that was provided on create.
func (u *AssetUpsert) UpdateTakenAt() *AssetUpsert {
	u.SetExcluded(asset.FieldTakenAt)
	return u
}

// ClearTakenAt clears the value of the "taken_at" field.
func (u *AssetUpsert) ClearTakenAt() *AssetUpsert {
	u.SetNull(asset.FieldTakenAt)
	return u
}

// SetHlsStatus sets the "hls_status" field.
func (u *AssetUpsert) SetHlsStatus(v asset.HlsStatus) *AssetUpsert {
	u.Set(asset.FieldHlsStatus, v)
	return u
}

// UpdateHlsStatus sets the "hls_status" field to the value that was provided on create.
func (u *AssetUpsert) UpdateHlsStatus() *AssetUpsert {
	u.SetExcluded(asset.FieldHlsStatus)
	return u
}

// SetHlsKey sets the "hls_key" field.
func (u *AssetUpsert) SetHlsKey(v string) *AssetUpsert {
	u.Set(asset.FieldHlsKey, v)
	return u
}

// UpdateHlsKey sets the "hls_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateHlsKey() *AssetUpsert {
	u.SetExcluded(asset.FieldHlsKey)
	return u
}

// ClearHlsKey clears the value of the "hls_key" field.
func (u *AssetUpsert) ClearHlsKey() *AssetUpsert {
	u.SetNull(asset.FieldHlsKey)
	return u
}

// SetThumbKey sets the "thumb_key" field.
func (u *AssetUpsert) SetThumbKey(v string) *AssetUpsert {
	u.Set(asset.FieldThumbKey, v)
	return u
}

// UpdateThumbKey sets the "thumb_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateThumbKey() *AssetUpsert {
	u.SetExcluded(asset.FieldThumbKey)
	return u
}

// ClearThumbKey clears the value of the "thumb_key" field.
func (u *AssetUpsert) ClearThumbKey() *AssetUpsert {
	u.SetNull(asset.FieldThumbKey)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AssetUpsert) SetSortOrder(v int) *AssetUpsert {
	u.Set(asset.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AssetUpsert) UpdateSortOrder() *AssetUpsert {
	u.SetExcluded(asset.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AssetUpsert) AddSortOrder(v int) *AssetUpsert {
	u.Add(asset.FieldSortOrder, v)
	return u
}

// SetIsLivePhoto sets the "is_live_photo" field.
func (u *AssetUpsert) SetIsLivePhoto(v bool) *AssetUpsert {
	u.Set(asset.FieldIsLivePhoto, v)
	return u
}

// UpdateIsLivePhoto sets the "is_live_photo" field to the value that was provided on create.
func (u *AssetUpsert) UpdateIsLivePhoto() *AssetUpsert {
	u.SetExcluded(asset.FieldIsLivePhoto)
	return u
}

// SetMotionKey sets the "motion_key" field.
func (u *AssetUpsert) SetMotionKey(v string) *AssetUpsert {
	u.Set(asset.FieldMotionKey, v)
	return u
}

// UpdateMotionKey sets the "motion_key" field to the value that was provided on create.
func (u *AssetUpsert) UpdateMotionKey() *AssetUpsert {
	u.SetExcluded(asset.FieldMotionKey)
	return u
}

// ClearMotionKey clears the value of the "motion_key" field.
func (u *AssetUpsert) ClearMotionKey() *AssetUpsert {
	u.SetNull(asset.FieldMotionKey)
	return u
}

// SetMotionMime sets the "motion_mime" field.
func (u *AssetUpsert) SetMotionMime(v string) *AssetUpsert {
	u.Set(asset.FieldMotionMime, v)
	return u
}

// UpdateMotionMime sets the "motion_mime" field to the value that was provided on create.
func (u *AssetUpsert) UpdateMotionMime() *AssetUpsert {
	u.SetExcluded(asset.FieldMotionMime)
	return u
}

// ClearMotionMime clears the value of the "motion_mime" field.
func (u *AssetUpsert) ClearMotionMime() *AssetUpsert {
	u.SetNull(asset.FieldMotionMime)
	return u
}

// SetExif sets the "exif" field.
func (u *AssetUpsert) SetExif(v map[string]interface{}) *AssetUpsert {
	u.Set(asset.FieldExif, v)
	return u
}

// UpdateExif sets the "exif" field to the value that was provided on create.
func (u *AssetUpsert) UpdateExif() *AssetUpsert {
	u.SetExcluded(asset.FieldExif)
	return u
}

// ClearExif clears the value of the "exif" field.
func (u *AssetUpsert) ClearExif() *AssetUpsert {
	u.SetNull(asset.FieldExif)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AssetUpsertOne) UpdateNewValues() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(asset.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AssetUpsertOne) Ignore() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetUpsertOne) DoNothing() *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetCreate.OnConflict
// documentation for more info.
func (u *AssetUpsertOne) Update(set func(*AssetUpsert)) *AssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsertOne) SetUpdatedAt(v time.Time) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateUpdatedAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTripID sets the "trip_id" field.
func (u *AssetUpsertOne) SetTripID(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetTripID(v)
	})
}

// UpdateTripID sets the "trip_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateTripID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTripID()
	})
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (u *AssetUpsertOne) SetUploadedByID(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetUploadedByID(v)
	})
}

// UpdateUploadedByID sets the "uploaded_by_id" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateUploadedByID() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUploadedByID()
	})
}

// SetKind sets the "kind" field.
func (u *AssetUpsertOne) SetKind(v asset.Kind) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateKind() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateKind()
	})
}

// SetOssKey sets the "oss_key" field.
func (u *AssetUpsertOne) SetOssKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetOssKey(v)
	})
}

// UpdateOssKey sets the "oss_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateOssKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateOssKey()
	})
}

// SetMime sets the "mime" field.
func (u *AssetUpsertOne) SetMime(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetMime(v)
	})
}

// UpdateMime sets the "mime" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateMime() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMime()
	})
}

// ClearMime clears the value of the "mime" field.
func (u *AssetUpsertOne) ClearMime() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMime()
	})
}

// SetSize sets the "size" field.
func (u *AssetUpsertOne) SetSize(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *AssetUpsertOne) AddSize(v int64) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateSize() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateSize()
	})
}

// SetWidth sets the "width" field.
func (u *AssetUpsertOne) SetWidth(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *AssetUpsertOne) AddWidth(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateWidth() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *AssetUpsertOne) ClearWidth() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *AssetUpsertOne) SetHeight(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *AssetUpsertOne) AddHeight(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateHeight() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *AssetUpsertOne) ClearHeight() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearHeight()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *AssetUpsertOne) SetDurationMs(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AssetUpsertOne) AddDurationMs(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateDurationMs() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AssetUpsertOne) ClearDurationMs() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDurationMs()
	})
}

// SetTakenAt sets the "taken_at" field.
func (u *AssetUpsertOne) SetTakenAt(v time.Time) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetTakenAt(v)
	})
}

// UpdateTakenAt sets the "taken_at" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateTakenAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTakenAt()
	})
}

// ClearTakenAt clears the value of the "taken_at" field.
func (u *AssetUpsertOne) ClearTakenAt() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearTakenAt()
	})
}

// SetHlsStatus sets the "hls_status" field.
func (u *AssetUpsertOne) SetHlsStatus(v asset.HlsStatus) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetHlsStatus(v)
	})
}

// UpdateHlsStatus sets the "hls_status" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateHlsStatus() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHlsStatus()
	})
}

// SetHlsKey sets the "hls_key" field.
func (u *AssetUpsertOne) SetHlsKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetHlsKey(v)
	})
}

// UpdateHlsKey sets the "hls_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateHlsKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHlsKey()
	})
}

// ClearHlsKey clears the value of the "hls_key" field.
func (u *AssetUpsertOne) ClearHlsKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearHlsKey()
	})
}

// SetThumbKey sets the "thumb_key" field.
func (u *AssetUpsertOne) SetThumbKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetThumbKey(v)
	})
}

// UpdateThumbKey sets the "thumb_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateThumbKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateThumbKey()
	})
}

// ClearThumbKey clears the value of the "thumb_key" field.
func (u *AssetUpsertOne) ClearThumbKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearThumbKey()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AssetUpsertOne) SetSortOrder(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AssetUpsertOne) AddSortOrder(v int) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateSortOrder() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsLivePhoto sets the "is_live_photo" field.
func (u *AssetUpsertOne) SetIsLivePhoto(v bool) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetIsLivePhoto(v)
	})
}

// UpdateIsLivePhoto sets the "is_live_photo" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateIsLivePhoto() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateIsLivePhoto()
	})
}

// SetMotionKey sets the "motion_key" field.
func (u *AssetUpsertOne) SetMotionKey(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetMotionKey(v)
	})
}

// UpdateMotionKey sets the "motion_key" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateMotionKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMotionKey()
	})
}

// ClearMotionKey clears the value of the "motion_key" field.
func (u *AssetUpsertOne) ClearMotionKey() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMotionKey()
	})
}

// SetMotionMime sets the "motion_mime" field.
func (u *AssetUpsertOne) SetMotionMime(v string) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetMotionMime(v)
	})
}

// UpdateMotionMime sets the "motion_mime" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateMotionMime() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMotionMime()
	})
}

// ClearMotionMime clears the value of the "motion_mime" field.
func (u *AssetUpsertOne) ClearMotionMime() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMotionMime()
	})
}

// SetExif sets the "exif" field.
func (u *AssetUpsertOne) SetExif(v map[string]interface{}) *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.SetExif(v)
	})
}

// UpdateExif sets the "exif" field to the value that was provided on create.
func (u *AssetUpsertOne) UpdateExif() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateExif()
	})
}

// ClearExif clears the value of the "exif" field.
func (u *AssetUpsertOne) ClearExif() *AssetUpsertOne {
	return u.Update(func(s *AssetUpsert) {
		s.ClearExif()
	})
}

// Exec executes the query.
func (u *AssetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AssetUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AssetUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
	conflict []sql.ConflictOption
}

// Save creates the Asset entities in the database.
func (_c *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Asset.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AssetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AssetCreateBulk) OnConflict(opts ...sql.ConflictOption) *AssetUpsertBulk {
	_c.conflict = opts
	return &AssetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AssetCreateBulk) OnConflictColumns(columns ...string) *AssetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AssetUpsertBulk{
		create: _c,
	}
}

// AssetUpsertBulk is the builder for "upsert"-ing
// a bulk of Asset nodes.
type AssetUpsertBulk struct {
	create *AssetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AssetUpsertBulk) UpdateNewValues() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(asset.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Asset.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AssetUpsertBulk) Ignore() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AssetUpsertBulk) DoNothing() *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AssetCreateBulk.OnConflict
// documentation for more info.
func (u *AssetUpsertBulk) Update(set func(*AssetUpsert)) *AssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AssetUpsertBulk) SetUpdatedAt(v time.Time) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateUpdatedAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTripID sets the "trip_id" field.
func (u *AssetUpsertBulk) SetTripID(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetTripID(v)
	})
}

// UpdateTripID sets the "trip_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateTripID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTripID()
	})
}

// SetUploadedByID sets the "uploaded_by_id" field.
func (u *AssetUpsertBulk) SetUploadedByID(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetUploadedByID(v)
	})
}

// UpdateUploadedByID sets the "uploaded_by_id" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateUploadedByID() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateUploadedByID()
	})
}

// SetKind sets the "kind" field.
func (u *AssetUpsertBulk) SetKind(v asset.Kind) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateKind() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateKind()
	})
}

// SetOssKey sets the "oss_key" field.
func (u *AssetUpsertBulk) SetOssKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetOssKey(v)
	})
}

// UpdateOssKey sets the "oss_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateOssKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateOssKey()
	})
}

// SetMime sets the "mime" field.
func (u *AssetUpsertBulk) SetMime(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetMime(v)
	})
}

// UpdateMime sets the "mime" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateMime() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMime()
	})
}

// ClearMime clears the value of the "mime" field.
func (u *AssetUpsertBulk) ClearMime() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMime()
	})
}

// SetSize sets the "size" field.
func (u *AssetUpsertBulk) SetSize(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *AssetUpsertBulk) AddSize(v int64) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateSize() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateSize()
	})
}

// SetWidth sets the "width" field.
func (u *AssetUpsertBulk) SetWidth(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *AssetUpsertBulk) AddWidth(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateWidth() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *AssetUpsertBulk) ClearWidth() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *AssetUpsertBulk) SetHeight(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *AssetUpsertBulk) AddHeight(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateHeight() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *AssetUpsertBulk) ClearHeight() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearHeight()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *AssetUpsertBulk) SetDurationMs(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *AssetUpsertBulk) AddDurationMs(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateDurationMs() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *AssetUpsertBulk) ClearDurationMs() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearDurationMs()
	})
}

// SetTakenAt sets the "taken_at" field.
func (u *AssetUpsertBulk) SetTakenAt(v time.Time) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetTakenAt(v)
	})
}

// UpdateTakenAt sets the "taken_at" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateTakenAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateTakenAt()
	})
}

// ClearTakenAt clears the value of the "taken_at" field.
func (u *AssetUpsertBulk) ClearTakenAt() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearTakenAt()
	})
}

// SetHlsStatus sets the "hls_status" field.
func (u *AssetUpsertBulk) SetHlsStatus(v asset.HlsStatus) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetHlsStatus(v)
	})
}

// UpdateHlsStatus sets the "hls_status" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateHlsStatus() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHlsStatus()
	})
}

// SetHlsKey sets the "hls_key" field.
func (u *AssetUpsertBulk) SetHlsKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetHlsKey(v)
	})
}

// UpdateHlsKey sets the "hls_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateHlsKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateHlsKey()
	})
}

// ClearHlsKey clears the value of the "hls_key" field.
func (u *AssetUpsertBulk) ClearHlsKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearHlsKey()
	})
}

// SetThumbKey sets the "thumb_key" field.
func (u *AssetUpsertBulk) SetThumbKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetThumbKey(v)
	})
}

// UpdateThumbKey sets the "thumb_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateThumbKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateThumbKey()
	})
}

// ClearThumbKey clears the value of the "thumb_key" field.
func (u *AssetUpsertBulk) ClearThumbKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearThumbKey()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AssetUpsertBulk) SetSortOrder(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AssetUpsertBulk) AddSortOrder(v int) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateSortOrder() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsLivePhoto sets the "is_live_photo" field.
func (u *AssetUpsertBulk) SetIsLivePhoto(v bool) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetIsLivePhoto(v)
	})
}

// UpdateIsLivePhoto sets the "is_live_photo" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateIsLivePhoto() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateIsLivePhoto()
	})
}

// SetMotionKey sets the "motion_key" field.
func (u *AssetUpsertBulk) SetMotionKey(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetMotionKey(v)
	})
}

// UpdateMotionKey sets the "motion_key" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateMotionKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMotionKey()
	})
}

// ClearMotionKey clears the value of the "motion_key" field.
func (u *AssetUpsertBulk) ClearMotionKey() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMotionKey()
	})
}

// SetMotionMime sets the "motion_mime" field.
func (u *AssetUpsertBulk) SetMotionMime(v string) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetMotionMime(v)
	})
}

// UpdateMotionMime sets the "motion_mime" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateMotionMime() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateMotionMime()
	})
}

// ClearMotionMime clears the value of the "motion_mime" field.
func (u *AssetUpsertBulk) ClearMotionMime() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearMotionMime()
	})
}

// SetExif sets the "exif" field.
func (u *AssetUpsertBulk) SetExif(v map[string]interface{}) *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.SetExif(v)
	})
}

// UpdateExif sets the "exif" field to the value that was provided on create.
func (u *AssetUpsertBulk) UpdateExif() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.UpdateExif()
	})
}

// ClearExif clears the value of the "exif" field.
func (u *AssetUpsertBulk) ClearExif() *AssetUpsertBulk {
	return u.Update(func(s *AssetUpsert) {
		s.ClearExif()
	})
}

// Exec executes the query.
func (u *AssetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AssetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AssetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AssetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
