// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/cloverstd/travel-moments/internal/ent/appsetting"
	"github.com/cloverstd/travel-moments/internal/ent/asset"
	"github.com/cloverstd/travel-moments/internal/ent/assetview"
	"github.com/cloverstd/travel-moments/internal/ent/auditlog"
	"github.com/cloverstd/travel-moments/internal/ent/collection"
	"github.com/cloverstd/travel-moments/internal/ent/collectionasset"
	"github.com/cloverstd/travel-moments/internal/ent/comment"
	"github.com/cloverstd/travel-moments/internal/ent/schema"
	"github.com/cloverstd/travel-moments/internal/ent/sharelink"
	"github.com/cloverstd/travel-moments/internal/ent/sharetrip"
	"github.com/cloverstd/travel-moments/internal/ent/trip"
	"github.com/cloverstd/travel-moments/internal/ent/tripeditor"
	"github.com/cloverstd/travel-moments/internal/ent/uploadgrant"
	"github.com/cloverstd/travel-moments/internal/ent/user"
	"github.com/cloverstd/travel-moments/internal/ent/usercredential"
	"github.com/cloverstd/travel-moments/internal/ent/visit"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appsettingMixin := schema.AppSetting{}.Mixin()
	appsettingMixinFields0 := appsettingMixin[0].Fields()
	_ = appsettingMixinFields0
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescCreatedAt is the schema descriptor for created_at field.
	appsettingDescCreatedAt := appsettingMixinFields0[0].Descriptor()
	// appsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsetting.DefaultCreatedAt = appsettingDescCreatedAt.Default.(func() time.Time)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingMixinFields0[1].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appsettingDescKey is the schema descriptor for key field.
	appsettingDescKey := appsettingFields[0].Descriptor()
	// appsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	appsetting.KeyValidator = func() func(string) error {
		validators := appsettingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	assetMixin := schema.Asset{}.Mixin()
	assetMixinFields0 := assetMixin[0].Fields()
	_ = assetMixinFields0
	assetFields := schema.Asset{}.Fields()
	_ = assetFields
	// assetDescCreatedAt is the schema descriptor for created_at field.
	assetDescCreatedAt := assetMixinFields0[0].Descriptor()
	// asset.DefaultCreatedAt holds the default value on creation for the created_at field.
	asset.DefaultCreatedAt = assetDescCreatedAt.Default.(func() time.Time)
	// assetDescUpdatedAt is the schema descriptor for updated_at field.
	assetDescUpdatedAt := assetMixinFields0[1].Descriptor()
	// asset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	asset.DefaultUpdatedAt = assetDescUpdatedAt.Default.(func() time.Time)
	// asset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	asset.UpdateDefaultUpdatedAt = assetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// assetDescOssKey is the schema descriptor for oss_key field.
	assetDescOssKey := assetFields[3].Descriptor()
	// asset.OssKeyValidator is a validator for the "oss_key" field. It is called by the builders before save.
	asset.OssKeyValidator = assetDescOssKey.Validators[0].(func(string) error)
	// assetDescSize is the schema descriptor for size field.
	assetDescSize := assetFields[5].Descriptor()
	// asset.DefaultSize holds the default value on creation for the size field.
	asset.DefaultSize = assetDescSize.Default.(int64)
	// assetDescSortOrder is the schema descriptor for sort_order field.
	assetDescSortOrder := assetFields[13].Descriptor()
	// asset.DefaultSortOrder holds the default value on creation for the sort_order field.
	asset.DefaultSortOrder = assetDescSortOrder.Default.(int)
	// assetDescIsLivePhoto is the schema descriptor for is_live_photo field.
	assetDescIsLivePhoto := assetFields[14].Descriptor()
	// asset.DefaultIsLivePhoto holds the default value on creation for the is_live_photo field.
	asset.DefaultIsLivePhoto = assetDescIsLivePhoto.Default.(bool)
	assetviewMixin := schema.AssetView{}.Mixin()
	assetviewMixinFields0 := assetviewMixin[0].Fields()
	_ = assetviewMixinFields0
	assetviewFields := schema.AssetView{}.Fields()
	_ = assetviewFields
	// assetviewDescCreatedAt is the schema descriptor for created_at field.
	assetviewDescCreatedAt := assetviewMixinFields0[0].Descriptor()
	// assetview.DefaultCreatedAt holds the default value on creation for the created_at field.
	assetview.DefaultCreatedAt = assetviewDescCreatedAt.Default.(func() time.Time)
	// assetviewDescUpdatedAt is the schema descriptor for updated_at field.
	assetviewDescUpdatedAt := assetviewMixinFields0[1].Descriptor()
	// assetview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	assetview.DefaultUpdatedAt = assetviewDescUpdatedAt.Default.(func() time.Time)
	// assetview.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	assetview.UpdateDefaultUpdatedAt = assetviewDescUpdatedAt.UpdateDefault.(func() time.Time)
	// assetviewDescBytesSigned is the schema descriptor for bytes_signed field.
	assetviewDescBytesSigned := assetviewFields[3].Descriptor()
	// assetview.DefaultBytesSigned holds the default value on creation for the bytes_signed field.
	assetview.DefaultBytesSigned = assetviewDescBytesSigned.Default.(int64)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = func() func(string) error {
		validators := auditlogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditlogDescTargetType is the schema descriptor for target_type field.
	auditlogDescTargetType := auditlogFields[2].Descriptor()
	// auditlog.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	auditlog.TargetTypeValidator = auditlogDescTargetType.Validators[0].(func(string) error)
	collectionMixin := schema.Collection{}.Mixin()
	collectionMixinFields0 := collectionMixin[0].Fields()
	_ = collectionMixinFields0
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescCreatedAt is the schema descriptor for created_at field.
	collectionDescCreatedAt := collectionMixinFields0[0].Descriptor()
	// collection.DefaultCreatedAt holds the default value on creation for the created_at field.
	collection.DefaultCreatedAt = collectionDescCreatedAt.Default.(func() time.Time)
	// collectionDescUpdatedAt is the schema descriptor for updated_at field.
	collectionDescUpdatedAt := collectionMixinFields0[1].Descriptor()
	// collection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	collection.DefaultUpdatedAt = collectionDescUpdatedAt.Default.(func() time.Time)
	// collection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	collection.UpdateDefaultUpdatedAt = collectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// collectionDescTitle is the schema descriptor for title field.
	collectionDescTitle := collectionFields[2].Descriptor()
	// collection.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	collection.TitleValidator = func() func(string) error {
		validators := collectionDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	collectionassetFields := schema.CollectionAsset{}.Fields()
	_ = collectionassetFields
	// collectionassetDescSortOrder is the schema descriptor for sort_order field.
	collectionassetDescSortOrder := collectionassetFields[2].Descriptor()
	// collectionasset.DefaultSortOrder holds the default value on creation for the sort_order field.
	collectionasset.DefaultSortOrder = collectionassetDescSortOrder.Default.(int)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[0].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescDisplayName is the schema descriptor for display_name field.
	commentDescDisplayName := commentFields[5].Descriptor()
	// comment.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	comment.DisplayNameValidator = func() func(string) error {
		validators := commentDescDisplayName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(display_name string) error {
			for _, fn := range fns {
				if err := fn(display_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[6].Descriptor()
	// comment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	comment.ContentValidator = func() func(string) error {
		validators := commentDescContent.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content string) error {
			for _, fn := range fns {
				if err := fn(content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commentDescColor is the schema descriptor for color field.
	commentDescColor := commentFields[7].Descriptor()
	// comment.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	comment.ColorValidator = commentDescColor.Validators[0].(func(string) error)
	sharelinkMixin := schema.ShareLink{}.Mixin()
	sharelinkMixinFields0 := sharelinkMixin[0].Fields()
	_ = sharelinkMixinFields0
	sharelinkFields := schema.ShareLink{}.Fields()
	_ = sharelinkFields
	// sharelinkDescCreatedAt is the schema descriptor for created_at field.
	sharelinkDescCreatedAt := sharelinkMixinFields0[0].Descriptor()
	// sharelink.DefaultCreatedAt holds the default value on creation for the created_at field.
	sharelink.DefaultCreatedAt = sharelinkDescCreatedAt.Default.(func() time.Time)
	// sharelinkDescUpdatedAt is the schema descriptor for updated_at field.
	sharelinkDescUpdatedAt := sharelinkMixinFields0[1].Descriptor()
	// sharelink.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sharelink.DefaultUpdatedAt = sharelinkDescUpdatedAt.Default.(func() time.Time)
	// sharelink.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sharelink.UpdateDefaultUpdatedAt = sharelinkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sharelinkDescCode is the schema descriptor for code field.
	sharelinkDescCode := sharelinkFields[4].Descriptor()
	// sharelink.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	sharelink.CodeValidator = func() func(string) error {
		validators := sharelinkDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharelinkDescNote is the schema descriptor for note field.
	sharelinkDescNote := sharelinkFields[9].Descriptor()
	// sharelink.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	sharelink.NoteValidator = sharelinkDescNote.Validators[0].(func(string) error)
	// sharelinkDescDisableForward is the schema descriptor for disable_forward field.
	sharelinkDescDisableForward := sharelinkFields[13].Descriptor()
	// sharelink.DefaultDisableForward holds the default value on creation for the disable_forward field.
	sharelink.DefaultDisableForward = sharelinkDescDisableForward.Default.(bool)
	sharetripMixin := schema.ShareTrip{}.Mixin()
	sharetripMixinFields0 := sharetripMixin[0].Fields()
	_ = sharetripMixinFields0
	sharetripFields := schema.ShareTrip{}.Fields()
	_ = sharetripFields
	// sharetripDescCreatedAt is the schema descriptor for created_at field.
	sharetripDescCreatedAt := sharetripMixinFields0[0].Descriptor()
	// sharetrip.DefaultCreatedAt holds the default value on creation for the created_at field.
	sharetrip.DefaultCreatedAt = sharetripDescCreatedAt.Default.(func() time.Time)
	// sharetripDescUpdatedAt is the schema descriptor for updated_at field.
	sharetripDescUpdatedAt := sharetripMixinFields0[1].Descriptor()
	// sharetrip.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sharetrip.DefaultUpdatedAt = sharetripDescUpdatedAt.Default.(func() time.Time)
	// sharetrip.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sharetrip.UpdateDefaultUpdatedAt = sharetripDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sharetripDescSortOrder is the schema descriptor for sort_order field.
	sharetripDescSortOrder := sharetripFields[2].Descriptor()
	// sharetrip.DefaultSortOrder holds the default value on creation for the sort_order field.
	sharetrip.DefaultSortOrder = sharetripDescSortOrder.Default.(int)
	tripMixin := schema.Trip{}.Mixin()
	tripMixinFields0 := tripMixin[0].Fields()
	_ = tripMixinFields0
	tripFields := schema.Trip{}.Fields()
	_ = tripFields
	// tripDescCreatedAt is the schema descriptor for created_at field.
	tripDescCreatedAt := tripMixinFields0[0].Descriptor()
	// trip.DefaultCreatedAt holds the default value on creation for the created_at field.
	trip.DefaultCreatedAt = tripDescCreatedAt.Default.(func() time.Time)
	// tripDescUpdatedAt is the schema descriptor for updated_at field.
	tripDescUpdatedAt := tripMixinFields0[1].Descriptor()
	// trip.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	trip.DefaultUpdatedAt = tripDescUpdatedAt.Default.(func() time.Time)
	// trip.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	trip.UpdateDefaultUpdatedAt = tripDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tripDescSlug is the schema descriptor for slug field.
	tripDescSlug := tripFields[0].Descriptor()
	// trip.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	trip.SlugValidator = func() func(string) error {
		validators := tripDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tripDescTitle is the schema descriptor for title field.
	tripDescTitle := tripFields[1].Descriptor()
	// trip.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	trip.TitleValidator = func() func(string) error {
		validators := tripDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tripDescLocation is the schema descriptor for location field.
	tripDescLocation := tripFields[3].Descriptor()
	// trip.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	trip.LocationValidator = tripDescLocation.Validators[0].(func(string) error)
	// tripDescShowViewCounts is the schema descriptor for show_view_counts field.
	tripDescShowViewCounts := tripFields[8].Descriptor()
	// trip.DefaultShowViewCounts holds the default value on creation for the show_view_counts field.
	trip.DefaultShowViewCounts = tripDescShowViewCounts.Default.(bool)
	tripeditorMixin := schema.TripEditor{}.Mixin()
	tripeditorMixinFields0 := tripeditorMixin[0].Fields()
	_ = tripeditorMixinFields0
	tripeditorFields := schema.TripEditor{}.Fields()
	_ = tripeditorFields
	// tripeditorDescCreatedAt is the schema descriptor for created_at field.
	tripeditorDescCreatedAt := tripeditorMixinFields0[0].Descriptor()
	// tripeditor.DefaultCreatedAt holds the default value on creation for the created_at field.
	tripeditor.DefaultCreatedAt = tripeditorDescCreatedAt.Default.(func() time.Time)
	// tripeditorDescUpdatedAt is the schema descriptor for updated_at field.
	tripeditorDescUpdatedAt := tripeditorMixinFields0[1].Descriptor()
	// tripeditor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tripeditor.DefaultUpdatedAt = tripeditorDescUpdatedAt.Default.(func() time.Time)
	// tripeditor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tripeditor.UpdateDefaultUpdatedAt = tripeditorDescUpdatedAt.UpdateDefault.(func() time.Time)
	uploadgrantMixin := schema.UploadGrant{}.Mixin()
	uploadgrantMixinFields0 := uploadgrantMixin[0].Fields()
	_ = uploadgrantMixinFields0
	uploadgrantFields := schema.UploadGrant{}.Fields()
	_ = uploadgrantFields
	// uploadgrantDescCreatedAt is the schema descriptor for created_at field.
	uploadgrantDescCreatedAt := uploadgrantMixinFields0[0].Descriptor()
	// uploadgrant.DefaultCreatedAt holds the default value on creation for the created_at field.
	uploadgrant.DefaultCreatedAt = uploadgrantDescCreatedAt.Default.(func() time.Time)
	// uploadgrantDescUpdatedAt is the schema descriptor for updated_at field.
	uploadgrantDescUpdatedAt := uploadgrantMixinFields0[1].Descriptor()
	// uploadgrant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	uploadgrant.DefaultUpdatedAt = uploadgrantDescUpdatedAt.Default.(func() time.Time)
	// uploadgrant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	uploadgrant.UpdateDefaultUpdatedAt = uploadgrantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// uploadgrantDescCode is the schema descriptor for code field.
	uploadgrantDescCode := uploadgrantFields[0].Descriptor()
	// uploadgrant.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	uploadgrant.CodeValidator = func() func(string) error {
		validators := uploadgrantDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadgrantDescTokenHash is the schema descriptor for token_hash field.
	uploadgrantDescTokenHash := uploadgrantFields[1].Descriptor()
	// uploadgrant.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	uploadgrant.TokenHashValidator = uploadgrantDescTokenHash.Validators[0].(func(string) error)
	// uploadgrantDescNote is the schema descriptor for note field.
	uploadgrantDescNote := uploadgrantFields[4].Descriptor()
	// uploadgrant.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	uploadgrant.NoteValidator = uploadgrantDescNote.Validators[0].(func(string) error)
	// uploadgrantDescConsumedIP is the schema descriptor for consumed_ip field.
	uploadgrantDescConsumedIP := uploadgrantFields[7].Descriptor()
	// uploadgrant.ConsumedIPValidator is a validator for the "consumed_ip" field. It is called by the builders before save.
	uploadgrant.ConsumedIPValidator = uploadgrantDescConsumedIP.Validators[0].(func(string) error)
	// uploadgrantDescConsumedUa is the schema descriptor for consumed_ua field.
	uploadgrantDescConsumedUa := uploadgrantFields[8].Descriptor()
	// uploadgrant.ConsumedUaValidator is a validator for the "consumed_ua" field. It is called by the builders before save.
	uploadgrant.ConsumedUaValidator = uploadgrantDescConsumedUa.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[3].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	usercredentialMixin := schema.UserCredential{}.Mixin()
	usercredentialMixinFields0 := usercredentialMixin[0].Fields()
	_ = usercredentialMixinFields0
	usercredentialFields := schema.UserCredential{}.Fields()
	_ = usercredentialFields
	// usercredentialDescCreatedAt is the schema descriptor for created_at field.
	usercredentialDescCreatedAt := usercredentialMixinFields0[0].Descriptor()
	// usercredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	usercredential.DefaultCreatedAt = usercredentialDescCreatedAt.Default.(func() time.Time)
	// usercredentialDescUpdatedAt is the schema descriptor for updated_at field.
	usercredentialDescUpdatedAt := usercredentialMixinFields0[1].Descriptor()
	// usercredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usercredential.DefaultUpdatedAt = usercredentialDescUpdatedAt.Default.(func() time.Time)
	// usercredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usercredential.UpdateDefaultUpdatedAt = usercredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usercredentialDescName is the schema descriptor for name field.
	usercredentialDescName := usercredentialFields[1].Descriptor()
	// usercredential.NameValidator is a validator for the "name" field. It is called by the builders before save.
	usercredential.NameValidator = usercredentialDescName.Validators[0].(func(string) error)
	// usercredentialDescAttestationType is the schema descriptor for attestation_type field.
	usercredentialDescAttestationType := usercredentialFields[4].Descriptor()
	// usercredential.AttestationTypeValidator is a validator for the "attestation_type" field. It is called by the builders before save.
	usercredential.AttestationTypeValidator = usercredentialDescAttestationType.Validators[0].(func(string) error)
	// usercredentialDescSignCount is the schema descriptor for sign_count field.
	usercredentialDescSignCount := usercredentialFields[6].Descriptor()
	// usercredential.DefaultSignCount holds the default value on creation for the sign_count field.
	usercredential.DefaultSignCount = usercredentialDescSignCount.Default.(uint32)
	// usercredentialDescTransports is the schema descriptor for transports field.
	usercredentialDescTransports := usercredentialFields[7].Descriptor()
	// usercredential.TransportsValidator is a validator for the "transports" field. It is called by the builders before save.
	usercredential.TransportsValidator = usercredentialDescTransports.Validators[0].(func(string) error)
	// usercredentialDescBackupEligible is the schema descriptor for backup_eligible field.
	usercredentialDescBackupEligible := usercredentialFields[8].Descriptor()
	// usercredential.DefaultBackupEligible holds the default value on creation for the backup_eligible field.
	usercredential.DefaultBackupEligible = usercredentialDescBackupEligible.Default.(bool)
	// usercredentialDescBackupState is the schema descriptor for backup_state field.
	usercredentialDescBackupState := usercredentialFields[9].Descriptor()
	// usercredential.DefaultBackupState holds the default value on creation for the backup_state field.
	usercredential.DefaultBackupState = usercredentialDescBackupState.Default.(bool)
	visitMixin := schema.Visit{}.Mixin()
	visitMixinFields0 := visitMixin[0].Fields()
	_ = visitMixinFields0
	visitFields := schema.Visit{}.Fields()
	_ = visitFields
	// visitDescCreatedAt is the schema descriptor for created_at field.
	visitDescCreatedAt := visitMixinFields0[0].Descriptor()
	// visit.DefaultCreatedAt holds the default value on creation for the created_at field.
	visit.DefaultCreatedAt = visitDescCreatedAt.Default.(func() time.Time)
	// visitDescUpdatedAt is the schema descriptor for updated_at field.
	visitDescUpdatedAt := visitMixinFields0[1].Descriptor()
	// visit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	visit.DefaultUpdatedAt = visitDescUpdatedAt.Default.(func() time.Time)
	// visit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	visit.UpdateDefaultUpdatedAt = visitDescUpdatedAt.UpdateDefault.(func() time.Time)
	// visitDescSessionID is the schema descriptor for session_id field.
	visitDescSessionID := visitFields[1].Descriptor()
	// visit.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	visit.SessionIDValidator = func() func(string) error {
		validators := visitDescSessionID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(session_id string) error {
			for _, fn := range fns {
				if err := fn(session_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// visitDescIP is the schema descriptor for ip field.
	visitDescIP := visitFields[2].Descriptor()
	// visit.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	visit.IPValidator = visitDescIP.Validators[0].(func(string) error)
	// visitDescUa is the schema descriptor for ua field.
	visitDescUa := visitFields[3].Descriptor()
	// visit.UaValidator is a validator for the "ua" field. It is called by the builders before save.
	visit.UaValidator = visitDescUa.Validators[0].(func(string) error)
	// visitDescReferer is the schema descriptor for referer field.
	visitDescReferer := visitFields[4].Descriptor()
	// visit.RefererValidator is a validator for the "referer" field. It is called by the builders before save.
	visit.RefererValidator = visitDescReferer.Validators[0].(func(string) error)
	// visitDescCountry is the schema descriptor for country field.
	visitDescCountry := visitFields[5].Descriptor()
	// visit.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	visit.CountryValidator = visitDescCountry.Validators[0].(func(string) error)
}
