// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/travel-moments/internal/ent/predicate"
	"github.com/cloverstd/travel-moments/internal/ent/sharelink"
	"github.com/cloverstd/travel-moments/internal/ent/sharetrip"
	"github.com/cloverstd/travel-moments/internal/ent/trip"
)

// ShareTripQuery is the builder for querying ShareTrip entities.
type ShareTripQuery struct {
	config
	ctx        *QueryContext
	order      []sharetrip.OrderOption
	inters     []Interceptor
	predicates []predicate.ShareTrip
	withShare  *ShareLinkQuery
	withTrip   *TripQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShareTripQuery builder.
func (_q *ShareTripQuery) Where(ps ...predicate.ShareTrip) *ShareTripQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ShareTripQuery) Limit(limit int) *ShareTripQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ShareTripQuery) Offset(offset int) *ShareTripQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ShareTripQuery) Unique(unique bool) *ShareTripQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ShareTripQuery) Order(o ...sharetrip.OrderOption) *ShareTripQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryShare chains the current query on the "share" edge.
func (_q *ShareTripQuery) QueryShare() *ShareLinkQuery {
	query := (&ShareLinkClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharetrip.Table, sharetrip.FieldID, selector),
			sqlgraph.To(sharelink.Table, sharelink.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sharetrip.ShareTable, sharetrip.ShareColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTrip chains the current query on the "trip" edge.
func (_q *ShareTripQuery) QueryTrip() *TripQuery {
	query := (&TripClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharetrip.Table, sharetrip.FieldID, selector),
			sqlgraph.To(trip.Table, trip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sharetrip.TripTable, sharetrip.TripColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ShareTrip entity from the query.
// Returns a *NotFoundError when no ShareTrip was found.
func (_q *ShareTripQuery) First(ctx context.Context) (*ShareTrip, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sharetrip.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ShareTripQuery) FirstX(ctx context.Context) *ShareTrip {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ShareTrip ID from the query.
// Returns a *NotFoundError when no ShareTrip ID was found.
func (_q *ShareTripQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sharetrip.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ShareTripQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ShareTrip entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ShareTrip entity is found.
// Returns a *NotFoundError when no ShareTrip entities are found.
func (_q *ShareTripQuery) Only(ctx context.Context) (*ShareTrip, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sharetrip.Label}
	default:
		return nil, &NotSingularError{sharetrip.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ShareTripQuery) OnlyX(ctx context.Context) *ShareTrip {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ShareTrip ID in the query.
// Returns a *NotSingularError when more than one ShareTrip ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ShareTripQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sharetrip.Label}
	default:
		err = &NotSingularError{sharetrip.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ShareTripQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ShareTrips.
func (_q *ShareTripQuery) All(ctx context.Context) ([]*ShareTrip, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ShareTrip, *ShareTripQuery]()
	return withInterceptors[[]*ShareTrip](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ShareTripQuery) AllX(ctx context.Context) []*ShareTrip {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ShareTrip IDs.
func (_q *ShareTripQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sharetrip.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ShareTripQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ShareTripQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ShareTripQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ShareTripQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ShareTripQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ShareTripQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShareTripQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ShareTripQuery) Clone() *ShareTripQuery {
	if _q == nil {
		return nil
	}
	return &ShareTripQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]sharetrip.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ShareTrip{}, _q.predicates...),
		withShare:  _q.withShare.Clone(),
		withTrip:   _q.withTrip.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithShare tells the query-builder to eager-load the nodes that are connected to
// the "share" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShareTripQuery) WithShare(opts ...func(*ShareLinkQuery)) *ShareTripQuery {
	query := (&ShareLinkClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withShare = query
	return _q
}

// WithTrip tells the query-builder to eager-load the nodes that are connected to
// the "trip" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShareTripQuery) WithTrip(opts ...func(*TripQuery)) *ShareTripQuery {
	query := (&TripClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTrip = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ShareTrip.Query().
//		GroupBy(sharetrip.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ShareTripQuery) GroupBy(field string, fields ...string) *ShareTripGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShareTripGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sharetrip.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ShareTrip.Query().
//		Select(sharetrip.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ShareTripQuery) Select(fields ...string) *ShareTripSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ShareTripSelect{ShareTripQuery: _q}
	sbuild.label = sharetrip.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShareTripSelect configured with the given aggregations.
func (_q *ShareTripQuery) Aggregate(fns ...AggregateFunc) *ShareTripSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ShareTripQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sharetrip.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ShareTripQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ShareTrip, error) {
	var (
		nodes       = []*ShareTrip{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withShare != nil,
			_q.withTrip != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ShareTrip).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ShareTrip{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withShare; query != nil {
		if err := _q.loadShare(ctx, query, nodes, nil,
			func(n *ShareTrip, e *ShareLink) { n.Edges.Share = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTrip; query != nil {
		if err := _q.loadTrip(ctx, query, nodes, nil,
			func(n *ShareTrip, e *Trip) { n.Edges.Trip = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ShareTripQuery) loadShare(ctx context.Context, query *ShareLinkQuery, nodes []*ShareTrip, init func(*ShareTrip), assign func(*ShareTrip, *ShareLink)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ShareTrip)
	for i := range nodes {
		fk := nodes[i].ShareID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sharelink.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "share_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ShareTripQuery) loadTrip(ctx context.Context, query *TripQuery, nodes []*ShareTrip, init func(*ShareTrip), assign func(*ShareTrip, *Trip)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ShareTrip)
	for i := range nodes {
		fk := nodes[i].TripID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(trip.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "trip_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ShareTripQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ShareTripQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sharetrip.Table, sharetrip.Columns, sqlgraph.NewFieldSpec(sharetrip.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharetrip.FieldID)
		for i := range fields {
			if fields[i] != sharetrip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withShare != nil {
			_spec.Node.AddColumnOnce(sharetrip.FieldShareID)
		}
		if _q.withTrip != nil {
			_spec.Node.AddColumnOnce(sharetrip.FieldTripID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ShareTripQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sharetrip.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sharetrip.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ShareTripQuery) Modify(modifiers ...func(s *sql.Selector)) *ShareTripSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// ShareTripGroupBy is the group-by builder for ShareTrip entities.
type ShareTripGroupBy struct {
	selector
	build *ShareTripQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ShareTripGroupBy) Aggregate(fns ...AggregateFunc) *ShareTripGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ShareTripGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShareTripQuery, *ShareTripGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ShareTripGroupBy) sqlScan(ctx context.Context, root *ShareTripQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShareTripSelect is the builder for selecting fields of ShareTrip entities.
type ShareTripSelect struct {
	*ShareTripQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ShareTripSelect) Aggregate(fns ...AggregateFunc) *ShareTripSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ShareTripSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShareTripQuery, *ShareTripSelect](ctx, _s.ShareTripQuery, _s, _s.inters, v)
}

func (_s *ShareTripSelect) sqlScan(ctx context.Context, root *ShareTripQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ShareTripSelect) Modify(modifiers ...func(s *sql.Selector)) *ShareTripSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
