// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/travel-moments/internal/ent/asset"
	"github.com/cloverstd/travel-moments/internal/ent/collection"
	"github.com/cloverstd/travel-moments/internal/ent/sharelink"
	"github.com/cloverstd/travel-moments/internal/ent/sharetrip"
	"github.com/cloverstd/travel-moments/internal/ent/trip"
	"github.com/cloverstd/travel-moments/internal/ent/tripeditor"
	"github.com/cloverstd/travel-moments/internal/ent/uploadgrant"
	"github.com/cloverstd/travel-moments/internal/ent/user"
)

// TripCreate is the builder for creating a Trip entity.
type TripCreate struct {
	config
	mutation *TripMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TripCreate) SetCreatedAt(v time.Time) *TripCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TripCreate) SetNillableCreatedAt(v *time.Time) *TripCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TripCreate) SetUpdatedAt(v time.Time) *TripCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TripCreate) SetNillableUpdatedAt(v *time.Time) *TripCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *TripCreate) SetSlug(v string) *TripCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *TripCreate) SetTitle(v string) *TripCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TripCreate) SetDescription(v string) *TripCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TripCreate) SetNillableDescription(v *string) *TripCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *TripCreate) SetLocation(v string) *TripCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *TripCreate) SetNillableLocation(v *string) *TripCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *TripCreate) SetStartedAt(v time.Time) *TripCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *TripCreate) SetNillableStartedAt(v *time.Time) *TripCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *TripCreate) SetEndedAt(v time.Time) *TripCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *TripCreate) SetNillableEndedAt(v *time.Time) *TripCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetCoverAssetID sets the "cover_asset_id" field.
func (_c *TripCreate) SetCoverAssetID(v int) *TripCreate {
	_c.mutation.SetCoverAssetID(v)
	return _c
}

// SetNillableCoverAssetID sets the "cover_asset_id" field if the given value is not nil.
func (_c *TripCreate) SetNillableCoverAssetID(v *int) *TripCreate {
	if v != nil {
		_c.SetCoverAssetID(*v)
	}
	return _c
}

// SetCreatedByID sets the "created_by_id" field.
func (_c *TripCreate) SetCreatedByID(v int) *TripCreate {
	_c.mutation.SetCreatedByID(v)
	return _c
}

// SetShowViewCounts sets the "show_view_counts" field.
func (_c *TripCreate) SetShowViewCounts(v bool) *TripCreate {
	_c.mutation.SetShowViewCounts(v)
	return _c
}

// SetNillableShowViewCounts sets the "show_view_counts" field if the given value is not nil.
func (_c *TripCreate) SetNillableShowViewCounts(v *bool) *TripCreate {
	if v != nil {
		_c.SetShowViewCounts(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *TripCreate) SetCreatedBy(v *User) *TripCreate {
	return _c.SetCreatedByID(v.ID)
}

// AddEditorIDs adds the "editors" edge to the User entity by IDs.
func (_c *TripCreate) AddEditorIDs(ids ...int) *TripCreate {
	_c.mutation.AddEditorIDs(ids...)
	return _c
}

// AddEditors adds the "editors" edges to the User entity.
func (_c *TripCreate) AddEditors(v ...*User) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEditorIDs(ids...)
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_c *TripCreate) AddAssetIDs(ids ...int) *TripCreate {
	_c.mutation.AddAssetIDs(ids...)
	return _c
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_c *TripCreate) AddAssets(v ...*Asset) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetIDs(ids...)
}

// AddCollectionIDs adds the "collections" edge to the Collection entity by IDs.
func (_c *TripCreate) AddCollectionIDs(ids ...int) *TripCreate {
	_c.mutation.AddCollectionIDs(ids...)
	return _c
}

// AddCollections adds the "collections" edges to the Collection entity.
func (_c *TripCreate) AddCollections(v ...*Collection) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCollectionIDs(ids...)
}

// AddShareIDs adds the "shares" edge to the ShareLink entity by IDs.
func (_c *TripCreate) AddShareIDs(ids ...int) *TripCreate {
	_c.mutation.AddShareIDs(ids...)
	return _c
}

// AddShares adds the "shares" edges to the ShareLink entity.
func (_c *TripCreate) AddShares(v ...*ShareLink) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShareIDs(ids...)
}

// AddMultiShareIDs adds the "multi_shares" edge to the ShareLink entity by IDs.
func (_c *TripCreate) AddMultiShareIDs(ids ...int) *TripCreate {
	_c.mutation.AddMultiShareIDs(ids...)
	return _c
}

// AddMultiShares adds the "multi_shares" edges to the ShareLink entity.
func (_c *TripCreate) AddMultiShares(v ...*ShareLink) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMultiShareIDs(ids...)
}

// AddUploadGrantIDs adds the "upload_grants" edge to the UploadGrant entity by IDs.
func (_c *TripCreate) AddUploadGrantIDs(ids ...int) *TripCreate {
	_c.mutation.AddUploadGrantIDs(ids...)
	return _c
}

// AddUploadGrants adds the "upload_grants" edges to the UploadGrant entity.
func (_c *TripCreate) AddUploadGrants(v ...*UploadGrant) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUploadGrantIDs(ids...)
}

// AddTripEditorIDs adds the "trip_editors" edge to the TripEditor entity by IDs.
func (_c *TripCreate) AddTripEditorIDs(ids ...int) *TripCreate {
	_c.mutation.AddTripEditorIDs(ids...)
	return _c
}

// AddTripEditors adds the "trip_editors" edges to the TripEditor entity.
func (_c *TripCreate) AddTripEditors(v ...*TripEditor) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTripEditorIDs(ids...)
}

// AddShareTripIDs adds the "share_trips" edge to the ShareTrip entity by IDs.
func (_c *TripCreate) AddShareTripIDs(ids ...int) *TripCreate {
	_c.mutation.AddShareTripIDs(ids...)
	return _c
}

// AddShareTrips adds the "share_trips" edges to the ShareTrip entity.
func (_c *TripCreate) AddShareTrips(v ...*ShareTrip) *TripCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShareTripIDs(ids...)
}

// Mutation returns the TripMutation object of the builder.
func (_c *TripCreate) Mutation() *TripMutation {
	return _c.mutation
}

// Save creates the Trip in the database.
func (_c *TripCreate) Save(ctx context.Context) (*Trip, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TripCreate) SaveX(ctx context.Context) *Trip {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TripCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TripCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TripCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := trip.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := trip.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ShowViewCounts(); !ok {
		v := trip.DefaultShowViewCounts
		_c.mutation.SetShowViewCounts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TripCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Trip.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Trip.updated_at"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Trip.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := trip.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Trip.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Trip.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := trip.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Trip.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Location(); ok {
		if err := trip.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Trip.location": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedByID(); !ok {
		return &ValidationError{Name: "created_by_id", err: errors.New(`ent: missing required field "Trip.created_by_id"`)}
	}
	if _, ok := _c.mutation.ShowViewCounts(); !ok {
		return &ValidationError{Name: "show_view_counts", err: errors.New(`ent: missing required field "Trip.show_view_counts"`)}
	}
	if len(_c.mutation.CreatedByIDs()) == 0 {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required edge "Trip.created_by"`)}
	}
	return nil
}

func (_c *TripCreate) sqlSave(ctx context.Context) (*Trip, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TripCreate) createSpec() (*Trip, *sqlgraph.CreateSpec) {
	var (
		_node = &Trip{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trip.Table, sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(trip.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(trip.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(trip.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(trip.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(trip.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(trip.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(trip.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(trip.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.CoverAssetID(); ok {
		_spec.SetField(trip.FieldCoverAssetID, field.TypeInt, value)
		_node.CoverAssetID = &value
	}
	if value, ok := _c.mutation.ShowViewCounts(); ok {
		_spec.SetField(trip.FieldShowViewCounts, field.TypeBool, value)
		_node.ShowViewCounts = value
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trip.CreatedByTable,
			Columns: []string{trip.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedByID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EditorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   trip.EditorsTable,
			Columns: trip.EditorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TripEditorCreate{config: _c.config, mutation: newTripEditorMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   trip.AssetsTable,
			Columns: []string{trip.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   trip.CollectionsTable,
			Columns: []string{trip.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   trip.SharesTable,
			Columns: []string{trip.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MultiSharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   trip.MultiSharesTable,
			Columns: trip.MultiSharesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ShareTripCreate{config: _c.config, mutation: newShareTripMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UploadGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   trip.UploadGrantsTable,
			Columns: []string{trip.UploadGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uploadgrant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TripEditorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   trip.TripEditorsTable,
			Columns: []string{trip.TripEditorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tripeditor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShareTripsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   trip.ShareTripsTable,
			Columns: []string{trip.ShareTripsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharetrip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Trip.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TripUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TripCreate) OnConflict(opts ...sql.ConflictOption) *TripUpsertOne {
	_c.conflict = opts
	return &TripUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Trip.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TripCreate) OnConflictColumns(columns ...string) *TripUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TripUpsertOne{
		create: _c,
	}
}

type (
	// TripUpsertOne is the builder for "upsert"-ing
	//  one Trip node.
	TripUpsertOne struct {
		create *TripCreate
	}

	// TripUpsert is the "OnConflict" setter.
	TripUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TripUpsert) SetUpdatedAt(v time.Time) *TripUpsert {
	u.Set(trip.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TripUpsert) UpdateUpdatedAt() *TripUpsert {
	u.SetExcluded(trip.FieldUpdatedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *TripUpsert) SetSlug(v string) *TripUpsert {
	u.Set(trip.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TripUpsert) UpdateSlug() *TripUpsert {
	u.SetExcluded(trip.FieldSlug)
	return u
}

// SetTitle sets the "title" field.
func (u *TripUpsert) SetTitle(v string) *TripUpsert {
	u.Set(trip.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TripUpsert) UpdateTitle() *TripUpsert {
	u.SetExcluded(trip.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *TripUpsert) SetDescription(v string) *TripUpsert {
	u.Set(trip.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TripUpsert) UpdateDescription() *TripUpsert {
	u.SetExcluded(trip.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TripUpsert) ClearDescription() *TripUpsert {
	u.SetNull(trip.FieldDescription)
	return u
}

// SetLocation sets the "location" field.
func (u *TripUpsert) SetLocation(v string) *TripUpsert {
	u.Set(trip.FieldLocation, v)
	return u
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *TripUpsert) UpdateLocation() *TripUpsert {
	u.SetExcluded(trip.FieldLocation)
	return u
}

// ClearLocation clears the value of the "location" field.
func (u *TripUpsert) ClearLocation() *TripUpsert {
	u.SetNull(trip.FieldLocation)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *TripUpsert) SetStartedAt(v time.Time) *TripUpsert {
	u.Set(trip.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *TripUpsert) UpdateStartedAt() *TripUpsert {
	u.SetExcluded(trip.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *TripUpsert) ClearStartedAt() *TripUpsert {
	u.SetNull(trip.FieldStartedAt)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *TripUpsert) SetEndedAt(v time.Time) *TripUpsert {
	u.Set(trip.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *TripUpsert) UpdateEndedAt() *TripUpsert {
	u.SetExcluded(trip.FieldEndedAt)
	return u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *TripUpsert) ClearEndedAt() *TripUpsert {
	u.SetNull(trip.FieldEndedAt)
	return u
}

// SetCoverAssetID sets the "cover_asset_id" field.
func (u *TripUpsert) SetCoverAssetID(v int) *TripUpsert {
	u.Set(trip.FieldCoverAssetID, v)
	return u
}

// UpdateCoverAssetID sets the "cover_asset_id" field to the value that was provided on create.
func (u *TripUpsert) UpdateCoverAssetID() *TripUpsert {
	u.SetExcluded(trip.FieldCoverAssetID)
	return u
}

// AddCoverAssetID adds v to the "cover_asset_id" field.
func (u *TripUpsert) AddCoverAssetID(v int) *TripUpsert {
	u.Add(trip.FieldCoverAssetID, v)
	return u
}

// ClearCoverAssetID clears the value of the "cover_asset_id" field.
func (u *TripUpsert) ClearCoverAssetID() *TripUpsert {
	u.SetNull(trip.FieldCoverAssetID)
	return u
}

// SetCreatedByID sets the "created_by_id" field.
func (u *TripUpsert) SetCreatedByID(v int) *TripUpsert {
	u.Set(trip.FieldCreatedByID, v)
	return u
}

// UpdateCreatedByID sets the "created_by_id" field to the value that was provided on create.
func (u *TripUpsert) UpdateCreatedByID() *TripUpsert {
	u.SetExcluded(trip.FieldCreatedByID)
	return u
}

// SetShowViewCounts sets the "show_view_counts" field.
func (u *TripUpsert) SetShowViewCounts(v bool) *TripUpsert {
	u.Set(trip.FieldShowViewCounts, v)
	return u
}

// UpdateShowViewCounts sets the "show_view_counts" field to the value that was provided on create.
func (u *TripUpsert) UpdateShowViewCounts() *TripUpsert {
	u.SetExcluded(trip.FieldShowViewCounts)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Trip.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TripUpsertOne) UpdateNewValues() *TripUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(trip.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Trip.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TripUpsertOne) Ignore() *TripUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TripUpsertOne) DoNothing() *TripUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TripCreate.OnConflict
// documentation for more info.
func (u *TripUpsertOne) Update(set func(*TripUpsert)) *TripUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TripUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TripUpsertOne) SetUpdatedAt(v time.Time) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateUpdatedAt() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *TripUpsertOne) SetSlug(v string) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateSlug() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateSlug()
	})
}

// SetTitle sets the "title" field.
func (u *TripUpsertOne) SetTitle(v string) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateTitle() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *TripUpsertOne) SetDescription(v string) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateDescription() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TripUpsertOne) ClearDescription() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.ClearDescription()
	})
}

// SetLocation sets the "location" field.
func (u *TripUpsertOne) SetLocation(v string) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetLocation(v)
	})
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateLocation() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateLocation()
	})
}

// ClearLocation clears the value of the "location" field.
func (u *TripUpsertOne) ClearLocation() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.ClearLocation()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *TripUpsertOne) SetStartedAt(v time.Time) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateStartedAt() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *TripUpsertOne) ClearStartedAt() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.ClearStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *TripUpsertOne) SetEndedAt(v time.Time) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateEndedAt() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *TripUpsertOne) ClearEndedAt() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.ClearEndedAt()
	})
}

// SetCoverAssetID sets the "cover_asset_id" field.
func (u *TripUpsertOne) SetCoverAssetID(v int) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetCoverAssetID(v)
	})
}

// AddCoverAssetID adds v to the "cover_asset_id" field.
func (u *TripUpsertOne) AddCoverAssetID(v int) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.AddCoverAssetID(v)
	})
}

// UpdateCoverAssetID sets the "cover_asset_id" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateCoverAssetID() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateCoverAssetID()
	})
}

// ClearCoverAssetID clears the value of the "cover_asset_id" field.
func (u *TripUpsertOne) ClearCoverAssetID() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.ClearCoverAssetID()
	})
}

// SetCreatedByID sets the "created_by_id" field.
func (u *TripUpsertOne) SetCreatedByID(v int) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetCreatedByID(v)
	})
}

// UpdateCreatedByID sets the "created_by_id" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateCreatedByID() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateCreatedByID()
	})
}

// SetShowViewCounts sets the "show_view_counts" field.
func (u *TripUpsertOne) SetShowViewCounts(v bool) *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.SetShowViewCounts(v)
	})
}

// UpdateShowViewCounts sets the "show_view_counts" field to the value that was provided on create.
func (u *TripUpsertOne) UpdateShowViewCounts() *TripUpsertOne {
	return u.Update(func(s *TripUpsert) {
		s.UpdateShowViewCounts()
	})
}

// Exec executes the query.
func (u *TripUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TripCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TripUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TripUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TripUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TripCreateBulk is the builder for creating many Trip entities in bulk.
type TripCreateBulk struct {
	config
	err      error
	builders []*TripCreate
	conflict []sql.ConflictOption
}

// Save creates the Trip entities in the database.
func (_c *TripCreateBulk) Save(ctx context.Context) ([]*Trip, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Trip, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TripMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TripCreateBulk) SaveX(ctx context.Context) []*Trip {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TripCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TripCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Trip.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TripUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TripCreateBulk) OnConflict(opts ...sql.ConflictOption) *TripUpsertBulk {
	_c.conflict = opts
	return &TripUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Trip.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TripCreateBulk) OnConflictColumns(columns ...string) *TripUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TripUpsertBulk{
		create: _c,
	}
}

// TripUpsertBulk is the builder for "upsert"-ing
// a bulk of Trip nodes.
type TripUpsertBulk struct {
	create *TripCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Trip.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TripUpsertBulk) UpdateNewValues() *TripUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(trip.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Trip.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TripUpsertBulk) Ignore() *TripUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TripUpsertBulk) DoNothing() *TripUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TripCreateBulk.OnConflict
// documentation for more info.
func (u *TripUpsertBulk) Update(set func(*TripUpsert)) *TripUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TripUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TripUpsertBulk) SetUpdatedAt(v time.Time) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateUpdatedAt() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *TripUpsertBulk) SetSlug(v string) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateSlug() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateSlug()
	})
}

// SetTitle sets the "title" field.
func (u *TripUpsertBulk) SetTitle(v string) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateTitle() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *TripUpsertBulk) SetDescription(v string) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateDescription() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TripUpsertBulk) ClearDescription() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.ClearDescription()
	})
}

// SetLocation sets the "location" field.
func (u *TripUpsertBulk) SetLocation(v string) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetLocation(v)
	})
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateLocation() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateLocation()
	})
}

// ClearLocation clears the value of the "location" field.
func (u *TripUpsertBulk) ClearLocation() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.ClearLocation()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *TripUpsertBulk) SetStartedAt(v time.Time) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateStartedAt() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *TripUpsertBulk) ClearStartedAt() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.ClearStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *TripUpsertBulk) SetEndedAt(v time.Time) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateEndedAt() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *TripUpsertBulk) ClearEndedAt() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.ClearEndedAt()
	})
}

// SetCoverAssetID sets the "cover_asset_id" field.
func (u *TripUpsertBulk) SetCoverAssetID(v int) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetCoverAssetID(v)
	})
}

// AddCoverAssetID adds v to the "cover_asset_id" field.
func (u *TripUpsertBulk) AddCoverAssetID(v int) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.AddCoverAssetID(v)
	})
}

// UpdateCoverAssetID sets the "cover_asset_id" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateCoverAssetID() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateCoverAssetID()
	})
}

// ClearCoverAssetID clears the value of the "cover_asset_id" field.
func (u *TripUpsertBulk) ClearCoverAssetID() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.ClearCoverAssetID()
	})
}

// SetCreatedByID sets the "created_by_id" field.
func (u *TripUpsertBulk) SetCreatedByID(v int) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetCreatedByID(v)
	})
}

// UpdateCreatedByID sets the "created_by_id" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateCreatedByID() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateCreatedByID()
	})
}

// SetShowViewCounts sets the "show_view_counts" field.
func (u *TripUpsertBulk) SetShowViewCounts(v bool) *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.SetShowViewCounts(v)
	})
}

// UpdateShowViewCounts sets the "show_view_counts" field to the value that was provided on create.
func (u *TripUpsertBulk) UpdateShowViewCounts() *TripUpsertBulk {
	return u.Update(func(s *TripUpsert) {
		s.UpdateShowViewCounts()
	})
}

// Exec executes the query.
func (u *TripUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TripCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TripCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TripUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
