// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/travel-moments/internal/ent/trip"
	"github.com/cloverstd/travel-moments/internal/ent/tripeditor"
	"github.com/cloverstd/travel-moments/internal/ent/user"
)

// TripEditor is the model entity for the TripEditor schema.
type TripEditor struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TripID holds the value of the "trip_id" field.
	TripID int `json:"trip_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TripEditorQuery when eager-loading is set.
	Edges        TripEditorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TripEditorEdges holds the relations/edges for other nodes in the graph.
type TripEditorEdges struct {
	// Trip holds the value of the trip edge.
	Trip *Trip `json:"trip,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TripOrErr returns the Trip value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TripEditorEdges) TripOrErr() (*Trip, error) {
	if e.Trip != nil {
		return e.Trip, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: trip.Label}
	}
	return nil, &NotLoadedError{edge: "trip"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TripEditorEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TripEditor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tripeditor.FieldID, tripeditor.FieldTripID, tripeditor.FieldUserID:
			values[i] = new(sql.NullInt64)
		case tripeditor.FieldCreatedAt, tripeditor.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TripEditor fields.
func (_m *TripEditor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tripeditor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tripeditor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tripeditor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tripeditor.FieldTripID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trip_id", values[i])
			} else if value.Valid {
				_m.TripID = int(value.Int64)
			}
		case tripeditor.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TripEditor.
// This includes values selected through modifiers, order, etc.
func (_m *TripEditor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTrip queries the "trip" edge of the TripEditor entity.
func (_m *TripEditor) QueryTrip() *TripQuery {
	return NewTripEditorClient(_m.config).QueryTrip(_m)
}

// QueryUser queries the "user" edge of the TripEditor entity.
func (_m *TripEditor) QueryUser() *UserQuery {
	return NewTripEditorClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TripEditor.
// Note that you need to call TripEditor.Unwrap() before calling this method if this TripEditor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TripEditor) Update() *TripEditorUpdateOne {
	return NewTripEditorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TripEditor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TripEditor) Unwrap() *TripEditor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TripEditor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TripEditor) String() string {
	var builder strings.Builder
	builder.WriteString("TripEditor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("trip_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TripID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// TripEditors is a parsable slice of TripEditor.
type TripEditors []*TripEditor
