// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/travel-moments/internal/ent/user"
	"github.com/cloverstd/travel-moments/internal/ent/usercredential"
)

// UserCredential is the model entity for the UserCredential schema.
type UserCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CredentialID holds the value of the "credential_id" field.
	CredentialID []byte `json:"credential_id,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey []byte `json:"public_key,omitempty"`
	// AttestationType holds the value of the "attestation_type" field.
	AttestationType string `json:"attestation_type,omitempty"`
	// Aaguid holds the value of the "aaguid" field.
	Aaguid []byte `json:"aaguid,omitempty"`
	// SignCount holds the value of the "sign_count" field.
	SignCount uint32 `json:"sign_count,omitempty"`
	// Transports holds the value of the "transports" field.
	Transports string `json:"transports,omitempty"`
	// BackupEligible holds the value of the "backup_eligible" field.
	BackupEligible bool `json:"backup_eligible,omitempty"`
	// BackupState holds the value of the "backup_state" field.
	BackupState bool `json:"backup_state,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCredentialQuery when eager-loading is set.
	Edges        UserCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserCredentialEdges holds the relations/edges for other nodes in the graph.
type UserCredentialEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCredentialEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercredential.FieldCredentialID, usercredential.FieldPublicKey, usercredential.FieldAaguid:
			values[i] = new([]byte)
		case usercredential.FieldBackupEligible, usercredential.FieldBackupState:
			values[i] = new(sql.NullBool)
		case usercredential.FieldID, usercredential.FieldUserID, usercredential.FieldSignCount:
			values[i] = new(sql.NullInt64)
		case usercredential.FieldName, usercredential.FieldAttestationType, usercredential.FieldTransports:
			values[i] = new(sql.NullString)
		case usercredential.FieldCreatedAt, usercredential.FieldUpdatedAt, usercredential.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCredential fields.
func (_m *UserCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usercredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usercredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usercredential.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case usercredential.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case usercredential.FieldCredentialID:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credential_id", values[i])
			} else if value != nil {
				_m.CredentialID = *value
			}
		case usercredential.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case usercredential.FieldAttestationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attestation_type", values[i])
			} else if value.Valid {
				_m.AttestationType = value.String
			}
		case usercredential.FieldAaguid:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field aaguid", values[i])
			} else if value != nil {
				_m.Aaguid = *value
			}
		case usercredential.FieldSignCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sign_count", values[i])
			} else if value.Valid {
				_m.SignCount = uint32(value.Int64)
			}
		case usercredential.FieldTransports:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transports", values[i])
			} else if value.Valid {
				_m.Transports = value.String
			}
		case usercredential.FieldBackupEligible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backup_eligible", values[i])
			} else if value.Valid {
				_m.BackupEligible = value.Bool
			}
		case usercredential.FieldBackupState:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backup_state", values[i])
			} else if value.Valid {
				_m.BackupState = value.Bool
			}
		case usercredential.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCredential.
// This includes values selected through modifiers, order, etc.
func (_m *UserCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserCredential entity.
func (_m *UserCredential) QueryUser() *UserQuery {
	return NewUserCredentialClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserCredential.
// Note that you need to call UserCredential.Unwrap() before calling this method if this UserCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCredential) Update() *UserCredentialUpdateOne {
	return NewUserCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCredential) Unwrap() *UserCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCredential) String() string {
	var builder strings.Builder
	builder.WriteString("UserCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("credential_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialID))
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("attestation_type=")
	builder.WriteString(_m.AttestationType)
	builder.WriteString(", ")
	builder.WriteString("aaguid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aaguid))
	builder.WriteString(", ")
	builder.WriteString("sign_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignCount))
	builder.WriteString(", ")
	builder.WriteString("transports=")
	builder.WriteString(_m.Transports)
	builder.WriteString(", ")
	builder.WriteString("backup_eligible=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackupEligible))
	builder.WriteString(", ")
	builder.WriteString("backup_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackupState))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserCredentials is a parsable slice of UserCredential.
type UserCredentials []*UserCredential
