// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/travel-moments/internal/ent/assetview"
	"github.com/cloverstd/travel-moments/internal/ent/comment"
	"github.com/cloverstd/travel-moments/internal/ent/sharelink"
	"github.com/cloverstd/travel-moments/internal/ent/visit"
)

// VisitCreate is the builder for creating a Visit entity.
type VisitCreate struct {
	config
	mutation *VisitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VisitCreate) SetCreatedAt(v time.Time) *VisitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VisitCreate) SetNillableCreatedAt(v *time.Time) *VisitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VisitCreate) SetUpdatedAt(v time.Time) *VisitCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VisitCreate) SetNillableUpdatedAt(v *time.Time) *VisitCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetShareID sets the "share_id" field.
func (_c *VisitCreate) SetShareID(v int) *VisitCreate {
	_c.mutation.SetShareID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *VisitCreate) SetSessionID(v string) *VisitCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *VisitCreate) SetIP(v string) *VisitCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *VisitCreate) SetNillableIP(v *string) *VisitCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetUa sets the "ua" field.
func (_c *VisitCreate) SetUa(v string) *VisitCreate {
	_c.mutation.SetUa(v)
	return _c
}

// SetNillableUa sets the "ua" field if the given value is not nil.
func (_c *VisitCreate) SetNillableUa(v *string) *VisitCreate {
	if v != nil {
		_c.SetUa(*v)
	}
	return _c
}

// SetReferer sets the "referer" field.
func (_c *VisitCreate) SetReferer(v string) *VisitCreate {
	_c.mutation.SetReferer(v)
	return _c
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_c *VisitCreate) SetNillableReferer(v *string) *VisitCreate {
	if v != nil {
		_c.SetReferer(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *VisitCreate) SetCountry(v string) *VisitCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *VisitCreate) SetNillableCountry(v *string) *VisitCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetVisitedAt sets the "visited_at" field.
func (_c *VisitCreate) SetVisitedAt(v time.Time) *VisitCreate {
	_c.mutation.SetVisitedAt(v)
	return _c
}

// SetShare sets the "share" edge to the ShareLink entity.
func (_c *VisitCreate) SetShare(v *ShareLink) *VisitCreate {
	return _c.SetShareID(v.ID)
}

// AddAssetViewIDs adds the "asset_views" edge to the AssetView entity by IDs.
func (_c *VisitCreate) AddAssetViewIDs(ids ...int) *VisitCreate {
	_c.mutation.AddAssetViewIDs(ids...)
	return _c
}

// AddAssetViews adds the "asset_views" edges to the AssetView entity.
func (_c *VisitCreate) AddAssetViews(v ...*AssetView) *VisitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetViewIDs(ids...)
}

// AddCreatedShareIDs adds the "created_shares" edge to the ShareLink entity by IDs.
func (_c *VisitCreate) AddCreatedShareIDs(ids ...int) *VisitCreate {
	_c.mutation.AddCreatedShareIDs(ids...)
	return _c
}

// AddCreatedShares adds the "created_shares" edges to the ShareLink entity.
func (_c *VisitCreate) AddCreatedShares(v ...*ShareLink) *VisitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCreatedShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_c *VisitCreate) AddCommentIDs(ids ...int) *VisitCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the Comment entity.
func (_c *VisitCreate) AddComments(v ...*Comment) *VisitCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// Mutation returns the VisitMutation object of the builder.
func (_c *VisitCreate) Mutation() *VisitMutation {
	return _c.mutation
}

// Save creates the Visit in the database.
func (_c *VisitCreate) Save(ctx context.Context) (*Visit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VisitCreate) SaveX(ctx context.Context) *Visit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VisitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VisitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VisitCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := visit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := visit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VisitCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Visit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Visit.updated_at"`)}
	}
	if _, ok := _c.mutation.ShareID(); !ok {
		return &ValidationError{Name: "share_id", err: errors.New(`ent: missing required field "Visit.share_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Visit.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := visit.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Visit.session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := visit.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Visit.ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Ua(); ok {
		if err := visit.UaValidator(v); err != nil {
			return &ValidationError{Name: "ua", err: fmt.Errorf(`ent: validator failed for field "Visit.ua": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Referer(); ok {
		if err := visit.RefererValidator(v); err != nil {
			return &ValidationError{Name: "referer", err: fmt.Errorf(`ent: validator failed for field "Visit.referer": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := visit.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Visit.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VisitedAt(); !ok {
		return &ValidationError{Name: "visited_at", err: errors.New(`ent: missing required field "Visit.visited_at"`)}
	}
	if len(_c.mutation.ShareIDs()) == 0 {
		return &ValidationError{Name: "share", err: errors.New(`ent: missing required edge "Visit.share"`)}
	}
	return nil
}

func (_c *VisitCreate) sqlSave(ctx context.Context) (*Visit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VisitCreate) createSpec() (*Visit, *sqlgraph.CreateSpec) {
	var (
		_node = &Visit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(visit.Table, sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(visit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(visit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(visit.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(visit.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Ua(); ok {
		_spec.SetField(visit.FieldUa, field.TypeString, value)
		_node.Ua = value
	}
	if value, ok := _c.mutation.Referer(); ok {
		_spec.SetField(visit.FieldReferer, field.TypeString, value)
		_node.Referer = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(visit.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.VisitedAt(); ok {
		_spec.SetField(visit.FieldVisitedAt, field.TypeTime, value)
		_node.VisitedAt = value
	}
	if nodes := _c.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.ShareTable,
			Columns: []string{visit.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShareID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedSharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Visit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VisitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VisitCreate) OnConflict(opts ...sql.ConflictOption) *VisitUpsertOne {
	_c.conflict = opts
	return &VisitUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VisitCreate) OnConflictColumns(columns ...string) *VisitUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VisitUpsertOne{
		create: _c,
	}
}

type (
	// VisitUpsertOne is the builder for "upsert"-ing
	//  one Visit node.
	VisitUpsertOne struct {
		create *VisitCreate
	}

	// VisitUpsert is the "OnConflict" setter.
	VisitUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitUpsert) SetUpdatedAt(v time.Time) *VisitUpsert {
	u.Set(visit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitUpsert) UpdateUpdatedAt() *VisitUpsert {
	u.SetExcluded(visit.FieldUpdatedAt)
	return u
}

// SetShareID sets the "share_id" field.
func (u *VisitUpsert) SetShareID(v int) *VisitUpsert {
	u.Set(visit.FieldShareID, v)
	return u
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *VisitUpsert) UpdateShareID() *VisitUpsert {
	u.SetExcluded(visit.FieldShareID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *VisitUpsert) SetSessionID(v string) *VisitUpsert {
	u.Set(visit.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *VisitUpsert) UpdateSessionID() *VisitUpsert {
	u.SetExcluded(visit.FieldSessionID)
	return u
}

// SetIP sets the "ip" field.
func (u *VisitUpsert) SetIP(v string) *VisitUpsert {
	u.Set(visit.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *VisitUpsert) UpdateIP() *VisitUpsert {
	u.SetExcluded(visit.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *VisitUpsert) ClearIP() *VisitUpsert {
	u.SetNull(visit.FieldIP)
	return u
}

// SetUa sets the "ua" field.
func (u *VisitUpsert) SetUa(v string) *VisitUpsert {
	u.Set(visit.FieldUa, v)
	return u
}

// UpdateUa sets the "ua" field to the value that was provided on create.
func (u *VisitUpsert) UpdateUa() *VisitUpsert {
	u.SetExcluded(visit.FieldUa)
	return u
}

// ClearUa clears the value of the "ua" field.
func (u *VisitUpsert) ClearUa() *VisitUpsert {
	u.SetNull(visit.FieldUa)
	return u
}

// SetReferer sets the "referer" field.
func (u *VisitUpsert) SetReferer(v string) *VisitUpsert {
	u.Set(visit.FieldReferer, v)
	return u
}

// UpdateReferer sets the "referer" field to the value that was provided on create.
func (u *VisitUpsert) UpdateReferer() *VisitUpsert {
	u.SetExcluded(visit.FieldReferer)
	return u
}

// ClearReferer clears the value of the "referer" field.
func (u *VisitUpsert) ClearReferer() *VisitUpsert {
	u.SetNull(visit.FieldReferer)
	return u
}

// SetCountry sets the "country" field.
func (u *VisitUpsert) SetCountry(v string) *VisitUpsert {
	u.Set(visit.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCountry() *VisitUpsert {
	u.SetExcluded(visit.FieldCountry)
	return u
}

// ClearCountry clears the value of the "country" field.
func (u *VisitUpsert) ClearCountry() *VisitUpsert {
	u.SetNull(visit.FieldCountry)
	return u
}

// SetVisitedAt sets the "visited_at" field.
func (u *VisitUpsert) SetVisitedAt(v time.Time) *VisitUpsert {
	u.Set(visit.FieldVisitedAt, v)
	return u
}

// UpdateVisitedAt sets the "visited_at" field to the value that was provided on create.
func (u *VisitUpsert) UpdateVisitedAt() *VisitUpsert {
	u.SetExcluded(visit.FieldVisitedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VisitUpsertOne) UpdateNewValues() *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(visit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Visit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VisitUpsertOne) Ignore() *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VisitUpsertOne) DoNothing() *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VisitCreate.OnConflict
// documentation for more info.
func (u *VisitUpsertOne) Update(set func(*VisitUpsert)) *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VisitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitUpsertOne) SetUpdatedAt(v time.Time) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateUpdatedAt() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShareID sets the "share_id" field.
func (u *VisitUpsertOne) SetShareID(v int) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateShareID() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateShareID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *VisitUpsertOne) SetSessionID(v string) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateSessionID() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateSessionID()
	})
}

// SetIP sets the "ip" field.
func (u *VisitUpsertOne) SetIP(v string) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateIP() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *VisitUpsertOne) ClearIP() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearIP()
	})
}

// SetUa sets the "ua" field.
func (u *VisitUpsertOne) SetUa(v string) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetUa(v)
	})
}

// UpdateUa sets the "ua" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateUa() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateUa()
	})
}

// ClearUa clears the value of the "ua" field.
func (u *VisitUpsertOne) ClearUa() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearUa()
	})
}

// SetReferer sets the "referer" field.
func (u *VisitUpsertOne) SetReferer(v string) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetReferer(v)
	})
}

// UpdateReferer sets the "referer" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateReferer() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateReferer()
	})
}

// ClearReferer clears the value of the "referer" field.
func (u *VisitUpsertOne) ClearReferer() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearReferer()
	})
}

// SetCountry sets the "country" field.
func (u *VisitUpsertOne) SetCountry(v string) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCountry() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *VisitUpsertOne) ClearCountry() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCountry()
	})
}

// SetVisitedAt sets the "visited_at" field.
func (u *VisitUpsertOne) SetVisitedAt(v time.Time) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetVisitedAt(v)
	})
}

// UpdateVisitedAt sets the "visited_at" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateVisitedAt() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateVisitedAt()
	})
}

// Exec executes the query.
func (u *VisitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VisitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VisitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VisitUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VisitUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VisitCreateBulk is the builder for creating many Visit entities in bulk.
type VisitCreateBulk struct {
	config
	err      error
	builders []*VisitCreate
	conflict []sql.ConflictOption
}

// Save creates the Visit entities in the database.
func (_c *VisitCreateBulk) Save(ctx context.Context) ([]*Visit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Visit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VisitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VisitCreateBulk) SaveX(ctx context.Context) []*Visit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VisitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VisitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Visit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VisitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VisitCreateBulk) OnConflict(opts ...sql.ConflictOption) *VisitUpsertBulk {
	_c.conflict = opts
	return &VisitUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VisitCreateBulk) OnConflictColumns(columns ...string) *VisitUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VisitUpsertBulk{
		create: _c,
	}
}

// VisitUpsertBulk is the builder for "upsert"-ing
// a bulk of Visit nodes.
type VisitUpsertBulk struct {
	create *VisitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VisitUpsertBulk) UpdateNewValues() *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(visit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VisitUpsertBulk) Ignore() *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VisitUpsertBulk) DoNothing() *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VisitCreateBulk.OnConflict
// documentation for more info.
func (u *VisitUpsertBulk) Update(set func(*VisitUpsert)) *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VisitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitUpsertBulk) SetUpdatedAt(v time.Time) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateUpdatedAt() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShareID sets the "share_id" field.
func (u *VisitUpsertBulk) SetShareID(v int) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateShareID() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateShareID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *VisitUpsertBulk) SetSessionID(v string) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateSessionID() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateSessionID()
	})
}

// SetIP sets the "ip" field.
func (u *VisitUpsertBulk) SetIP(v string) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateIP() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *VisitUpsertBulk) ClearIP() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearIP()
	})
}

// SetUa sets the "ua" field.
func (u *VisitUpsertBulk) SetUa(v string) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetUa(v)
	})
}

// UpdateUa sets the "ua" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateUa() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateUa()
	})
}

// ClearUa clears the value of the "ua" field.
func (u *VisitUpsertBulk) ClearUa() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearUa()
	})
}

// SetReferer sets the "referer" field.
func (u *VisitUpsertBulk) SetReferer(v string) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetReferer(v)
	})
}

// UpdateReferer sets the "referer" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateReferer() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateReferer()
	})
}

// ClearReferer clears the value of the "referer" field.
func (u *VisitUpsertBulk) ClearReferer() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearReferer()
	})
}

// SetCountry sets the "country" field.
func (u *VisitUpsertBulk) SetCountry(v string) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCountry() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *VisitUpsertBulk) ClearCountry() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCountry()
	})
}

// SetVisitedAt sets the "visited_at" field.
func (u *VisitUpsertBulk) SetVisitedAt(v time.Time) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetVisitedAt(v)
	})
}

// UpdateVisitedAt sets the "visited_at" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateVisitedAt() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateVisitedAt()
	})
}

// Exec executes the query.
func (u *VisitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VisitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VisitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VisitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
