// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/travel-moments/internal/ent/assetview"
	"github.com/cloverstd/travel-moments/internal/ent/comment"
	"github.com/cloverstd/travel-moments/internal/ent/predicate"
	"github.com/cloverstd/travel-moments/internal/ent/sharelink"
	"github.com/cloverstd/travel-moments/internal/ent/visit"
)

// VisitUpdate is the builder for updating Visit entities.
type VisitUpdate struct {
	config
	hooks     []Hook
	mutation  *VisitMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the VisitUpdate builder.
func (_u *VisitUpdate) Where(ps ...predicate.Visit) *VisitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VisitUpdate) SetUpdatedAt(v time.Time) *VisitUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetShareID sets the "share_id" field.
func (_u *VisitUpdate) SetShareID(v int) *VisitUpdate {
	_u.mutation.SetShareID(v)
	return _u
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableShareID(v *int) *VisitUpdate {
	if v != nil {
		_u.SetShareID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *VisitUpdate) SetSessionID(v string) *VisitUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableSessionID(v *string) *VisitUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *VisitUpdate) SetIP(v string) *VisitUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableIP(v *string) *VisitUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *VisitUpdate) ClearIP() *VisitUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUa sets the "ua" field.
func (_u *VisitUpdate) SetUa(v string) *VisitUpdate {
	_u.mutation.SetUa(v)
	return _u
}

// SetNillableUa sets the "ua" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableUa(v *string) *VisitUpdate {
	if v != nil {
		_u.SetUa(*v)
	}
	return _u
}

// ClearUa clears the value of the "ua" field.
func (_u *VisitUpdate) ClearUa() *VisitUpdate {
	_u.mutation.ClearUa()
	return _u
}

// SetReferer sets the "referer" field.
func (_u *VisitUpdate) SetReferer(v string) *VisitUpdate {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableReferer(v *string) *VisitUpdate {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// ClearReferer clears the value of the "referer" field.
func (_u *VisitUpdate) ClearReferer() *VisitUpdate {
	_u.mutation.ClearReferer()
	return _u
}

// SetCountry sets the "country" field.
func (_u *VisitUpdate) SetCountry(v string) *VisitUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableCountry(v *string) *VisitUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *VisitUpdate) ClearCountry() *VisitUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetVisitedAt sets the "visited_at" field.
func (_u *VisitUpdate) SetVisitedAt(v time.Time) *VisitUpdate {
	_u.mutation.SetVisitedAt(v)
	return _u
}

// SetNillableVisitedAt sets the "visited_at" field if the given value is not nil.
func (_u *VisitUpdate) SetNillableVisitedAt(v *time.Time) *VisitUpdate {
	if v != nil {
		_u.SetVisitedAt(*v)
	}
	return _u
}

// SetShare sets the "share" edge to the ShareLink entity.
func (_u *VisitUpdate) SetShare(v *ShareLink) *VisitUpdate {
	return _u.SetShareID(v.ID)
}

// AddAssetViewIDs adds the "asset_views" edge to the AssetView entity by IDs.
func (_u *VisitUpdate) AddAssetViewIDs(ids ...int) *VisitUpdate {
	_u.mutation.AddAssetViewIDs(ids...)
	return _u
}

// AddAssetViews adds the "asset_views" edges to the AssetView entity.
func (_u *VisitUpdate) AddAssetViews(v ...*AssetView) *VisitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetViewIDs(ids...)
}

// AddCreatedShareIDs adds the "created_shares" edge to the ShareLink entity by IDs.
func (_u *VisitUpdate) AddCreatedShareIDs(ids ...int) *VisitUpdate {
	_u.mutation.AddCreatedShareIDs(ids...)
	return _u
}

// AddCreatedShares adds the "created_shares" edges to the ShareLink entity.
func (_u *VisitUpdate) AddCreatedShares(v ...*ShareLink) *VisitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *VisitUpdate) AddCommentIDs(ids ...int) *VisitUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *VisitUpdate) AddComments(v ...*Comment) *VisitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// Mutation returns the VisitMutation object of the builder.
func (_u *VisitUpdate) Mutation() *VisitMutation {
	return _u.mutation
}

// ClearShare clears the "share" edge to the ShareLink entity.
func (_u *VisitUpdate) ClearShare() *VisitUpdate {
	_u.mutation.ClearShare()
	return _u
}

// ClearAssetViews clears all "asset_views" edges to the AssetView entity.
func (_u *VisitUpdate) ClearAssetViews() *VisitUpdate {
	_u.mutation.ClearAssetViews()
	return _u
}

// RemoveAssetViewIDs removes the "asset_views" edge to AssetView entities by IDs.
func (_u *VisitUpdate) RemoveAssetViewIDs(ids ...int) *VisitUpdate {
	_u.mutation.RemoveAssetViewIDs(ids...)
	return _u
}

// RemoveAssetViews removes "asset_views" edges to AssetView entities.
func (_u *VisitUpdate) RemoveAssetViews(v ...*AssetView) *VisitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetViewIDs(ids...)
}

// ClearCreatedShares clears all "created_shares" edges to the ShareLink entity.
func (_u *VisitUpdate) ClearCreatedShares() *VisitUpdate {
	_u.mutation.ClearCreatedShares()
	return _u
}

// RemoveCreatedShareIDs removes the "created_shares" edge to ShareLink entities by IDs.
func (_u *VisitUpdate) RemoveCreatedShareIDs(ids ...int) *VisitUpdate {
	_u.mutation.RemoveCreatedShareIDs(ids...)
	return _u
}

// RemoveCreatedShares removes "created_shares" edges to ShareLink entities.
func (_u *VisitUpdate) RemoveCreatedShares(v ...*ShareLink) *VisitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedShareIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *VisitUpdate) ClearComments() *VisitUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *VisitUpdate) RemoveCommentIDs(ids ...int) *VisitUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *VisitUpdate) RemoveComments(v ...*Comment) *VisitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VisitUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VisitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VisitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VisitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VisitUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := visit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VisitUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := visit.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Visit.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := visit.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Visit.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ua(); ok {
		if err := visit.UaValidator(v); err != nil {
			return &ValidationError{Name: "ua", err: fmt.Errorf(`ent: validator failed for field "Visit.ua": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referer(); ok {
		if err := visit.RefererValidator(v); err != nil {
			return &ValidationError{Name: "referer", err: fmt.Errorf(`ent: validator failed for field "Visit.referer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := visit.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Visit.country": %w`, err)}
		}
	}
	if _u.mutation.ShareCleared() && len(_u.mutation.ShareIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Visit.share"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VisitUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VisitUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VisitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(visit.Table, visit.Columns, sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(visit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(visit.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(visit.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(visit.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.Ua(); ok {
		_spec.SetField(visit.FieldUa, field.TypeString, value)
	}
	if _u.mutation.UaCleared() {
		_spec.ClearField(visit.FieldUa, field.TypeString)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(visit.FieldReferer, field.TypeString, value)
	}
	if _u.mutation.RefererCleared() {
		_spec.ClearField(visit.FieldReferer, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(visit.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(visit.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.VisitedAt(); ok {
		_spec.SetField(visit.FieldVisitedAt, field.TypeTime, value)
	}
	if _u.mutation.ShareCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.ShareTable,
			Columns: []string{visit.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.ShareTable,
			Columns: []string{visit.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetViewsIDs(); len(nodes) > 0 && !_u.mutation.AssetViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedSharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedSharesIDs(); len(nodes) > 0 && !_u.mutation.CreatedSharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedSharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VisitUpdateOne is the builder for updating a single Visit entity.
type VisitUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *VisitMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VisitUpdateOne) SetUpdatedAt(v time.Time) *VisitUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetShareID sets the "share_id" field.
func (_u *VisitUpdateOne) SetShareID(v int) *VisitUpdateOne {
	_u.mutation.SetShareID(v)
	return _u
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableShareID(v *int) *VisitUpdateOne {
	if v != nil {
		_u.SetShareID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *VisitUpdateOne) SetSessionID(v string) *VisitUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableSessionID(v *string) *VisitUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *VisitUpdateOne) SetIP(v string) *VisitUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableIP(v *string) *VisitUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *VisitUpdateOne) ClearIP() *VisitUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUa sets the "ua" field.
func (_u *VisitUpdateOne) SetUa(v string) *VisitUpdateOne {
	_u.mutation.SetUa(v)
	return _u
}

// SetNillableUa sets the "ua" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableUa(v *string) *VisitUpdateOne {
	if v != nil {
		_u.SetUa(*v)
	}
	return _u
}

// ClearUa clears the value of the "ua" field.
func (_u *VisitUpdateOne) ClearUa() *VisitUpdateOne {
	_u.mutation.ClearUa()
	return _u
}

// SetReferer sets the "referer" field.
func (_u *VisitUpdateOne) SetReferer(v string) *VisitUpdateOne {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableReferer(v *string) *VisitUpdateOne {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// ClearReferer clears the value of the "referer" field.
func (_u *VisitUpdateOne) ClearReferer() *VisitUpdateOne {
	_u.mutation.ClearReferer()
	return _u
}

// SetCountry sets the "country" field.
func (_u *VisitUpdateOne) SetCountry(v string) *VisitUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableCountry(v *string) *VisitUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *VisitUpdateOne) ClearCountry() *VisitUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetVisitedAt sets the "visited_at" field.
func (_u *VisitUpdateOne) SetVisitedAt(v time.Time) *VisitUpdateOne {
	_u.mutation.SetVisitedAt(v)
	return _u
}

// SetNillableVisitedAt sets the "visited_at" field if the given value is not nil.
func (_u *VisitUpdateOne) SetNillableVisitedAt(v *time.Time) *VisitUpdateOne {
	if v != nil {
		_u.SetVisitedAt(*v)
	}
	return _u
}

// SetShare sets the "share" edge to the ShareLink entity.
func (_u *VisitUpdateOne) SetShare(v *ShareLink) *VisitUpdateOne {
	return _u.SetShareID(v.ID)
}

// AddAssetViewIDs adds the "asset_views" edge to the AssetView entity by IDs.
func (_u *VisitUpdateOne) AddAssetViewIDs(ids ...int) *VisitUpdateOne {
	_u.mutation.AddAssetViewIDs(ids...)
	return _u
}

// AddAssetViews adds the "asset_views" edges to the AssetView entity.
func (_u *VisitUpdateOne) AddAssetViews(v ...*AssetView) *VisitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetViewIDs(ids...)
}

// AddCreatedShareIDs adds the "created_shares" edge to the ShareLink entity by IDs.
func (_u *VisitUpdateOne) AddCreatedShareIDs(ids ...int) *VisitUpdateOne {
	_u.mutation.AddCreatedShareIDs(ids...)
	return _u
}

// AddCreatedShares adds the "created_shares" edges to the ShareLink entity.
func (_u *VisitUpdateOne) AddCreatedShares(v ...*ShareLink) *VisitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *VisitUpdateOne) AddCommentIDs(ids ...int) *VisitUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *VisitUpdateOne) AddComments(v ...*Comment) *VisitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// Mutation returns the VisitMutation object of the builder.
func (_u *VisitUpdateOne) Mutation() *VisitMutation {
	return _u.mutation
}

// ClearShare clears the "share" edge to the ShareLink entity.
func (_u *VisitUpdateOne) ClearShare() *VisitUpdateOne {
	_u.mutation.ClearShare()
	return _u
}

// ClearAssetViews clears all "asset_views" edges to the AssetView entity.
func (_u *VisitUpdateOne) ClearAssetViews() *VisitUpdateOne {
	_u.mutation.ClearAssetViews()
	return _u
}

// RemoveAssetViewIDs removes the "asset_views" edge to AssetView entities by IDs.
func (_u *VisitUpdateOne) RemoveAssetViewIDs(ids ...int) *VisitUpdateOne {
	_u.mutation.RemoveAssetViewIDs(ids...)
	return _u
}

// RemoveAssetViews removes "asset_views" edges to AssetView entities.
func (_u *VisitUpdateOne) RemoveAssetViews(v ...*AssetView) *VisitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetViewIDs(ids...)
}

// ClearCreatedShares clears all "created_shares" edges to the ShareLink entity.
func (_u *VisitUpdateOne) ClearCreatedShares() *VisitUpdateOne {
	_u.mutation.ClearCreatedShares()
	return _u
}

// RemoveCreatedShareIDs removes the "created_shares" edge to ShareLink entities by IDs.
func (_u *VisitUpdateOne) RemoveCreatedShareIDs(ids ...int) *VisitUpdateOne {
	_u.mutation.RemoveCreatedShareIDs(ids...)
	return _u
}

// RemoveCreatedShares removes "created_shares" edges to ShareLink entities.
func (_u *VisitUpdateOne) RemoveCreatedShares(v ...*ShareLink) *VisitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedShareIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *VisitUpdateOne) ClearComments() *VisitUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *VisitUpdateOne) RemoveCommentIDs(ids ...int) *VisitUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *VisitUpdateOne) RemoveComments(v ...*Comment) *VisitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// Where appends a list predicates to the VisitUpdate builder.
func (_u *VisitUpdateOne) Where(ps ...predicate.Visit) *VisitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VisitUpdateOne) Select(field string, fields ...string) *VisitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Visit entity.
func (_u *VisitUpdateOne) Save(ctx context.Context) (*Visit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VisitUpdateOne) SaveX(ctx context.Context) *Visit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VisitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VisitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VisitUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := visit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VisitUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := visit.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "Visit.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := visit.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Visit.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ua(); ok {
		if err := visit.UaValidator(v); err != nil {
			return &ValidationError{Name: "ua", err: fmt.Errorf(`ent: validator failed for field "Visit.ua": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referer(); ok {
		if err := visit.RefererValidator(v); err != nil {
			return &ValidationError{Name: "referer", err: fmt.Errorf(`ent: validator failed for field "Visit.referer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := visit.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Visit.country": %w`, err)}
		}
	}
	if _u.mutation.ShareCleared() && len(_u.mutation.ShareIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Visit.share"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VisitUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VisitUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VisitUpdateOne) sqlSave(ctx context.Context) (_node *Visit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(visit.Table, visit.Columns, sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Visit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visit.FieldID)
		for _, f := range fields {
			if !visit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != visit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(visit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(visit.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(visit.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(visit.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.Ua(); ok {
		_spec.SetField(visit.FieldUa, field.TypeString, value)
	}
	if _u.mutation.UaCleared() {
		_spec.ClearField(visit.FieldUa, field.TypeString)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(visit.FieldReferer, field.TypeString, value)
	}
	if _u.mutation.RefererCleared() {
		_spec.ClearField(visit.FieldReferer, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(visit.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(visit.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.VisitedAt(); ok {
		_spec.SetField(visit.FieldVisitedAt, field.TypeTime, value)
	}
	if _u.mutation.ShareCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.ShareTable,
			Columns: []string{visit.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visit.ShareTable,
			Columns: []string{visit.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetViewsIDs(); len(nodes) > 0 && !_u.mutation.AssetViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.AssetViewsTable,
			Columns: []string{visit.AssetViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetview.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedSharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedSharesIDs(); len(nodes) > 0 && !_u.mutation.CreatedSharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedSharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CreatedSharesTable,
			Columns: []string{visit.CreatedSharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharelink.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.CommentsTable,
			Columns: []string{visit.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Visit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
